### ISSUE TITLE
local-exec not firing when expected

### ISSUE THREAD

**Issue by jon-node28** [terraform-providers/terraform-provider-digitalocean#114]
Hi there,

I'm finding that the local-exec script is running long before the DO droplet has finishes creation.

### Terraform Version
terraform - v0.11.7
provider.digitalocean v0.1.3

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
```hcl
resource "digitalocean_volume" "user_files" {
  region      = "${var.region}"
  name        = "user_files"
  size        = 2
  description = "Volume containing user uploaded content such as profile images and CV documents"
}

resource "digitalocean_droplet" "dokku" {
  image  = "ubuntu-16-04-x64"
  name   = "App-Web"
  region = "lon1"
  size   = "s-4vcpu-8gb"
  monitoring = true
  private_networking = true
  ssh_keys = [ "${digitalocean_ssh_key.default.id}" ]
  # user_data = "${file("./cloud-init/upgrade.sh")}\n${file("./cloud-init/dokku-server.sh")}\n${file("./cloud-init/reboot.sh")}"
  volume_ids = [ "${digitalocean_volume.user_files.id}"]
  provisioner "local-exec" {
    command = <<EOF
      sleep 10
      ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u root --private-key ~/.ssh/app-do -i '${digitalocean_droplet.dokku.ipv4_address},' -e database_private_ip=${digitalocean_droplet.database.ipv4_address_private} ansible/web.yml
      EOF
  }
}

resource "digitalocean_floating_ip" "web_ip" {
  droplet_id = "${digitalocean_droplet.dokku.id}"
  region     = "${digitalocean_droplet.dokku.region}"
}

resource "digitalocean_firewall" "web" {
  name = "dokku-traffic"

  droplet_ids = [ "${digitalocean_droplet.dokku.id}" ]

  inbound_rule = [
    {
      protocol           = "tcp"
      port_range         = "22"
      source_addresses   = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol           = "tcp"
      port_range         = "80"
      source_addresses   = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol           = "tcp"
      port_range         = "443"
      source_addresses   = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol            = "icmp"
      source_addresses    = ["${digitalocean_droplet.database.ipv4_address_private}"]
    }
  ]

  outbound_rule = [
    {
      protocol                = "tcp"
      port_range              = "1-65535"
      destination_addresses   = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol                = "udp"
      port_range              = "1-65535"
      destination_addresses   = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol                = "icmp"
      destination_addresses   = ["0.0.0.0/0", "::/0"]
    }
  ]
}
```

### Debug Output
digitalocean_droplet.database: Creating...
  disk:                 "" => "<computed>"
  image:                "" => "ubuntu-16-04-x64"
  ipv4_address:         "" => "<computed>"
  ipv4_address_private: "" => "<computed>"
  ipv6_address:         "" => "<computed>"
  ipv6_address_private: "" => "<computed>"
  locked:               "" => "<computed>"
  monitoring:           "" => "true"
  name:                 "" => "App-Database"
  price_hourly:         "" => "<computed>"
  price_monthly:        "" => "<computed>"
  private_networking:   "" => "true"
  region:               "" => "lon1"
  resize_disk:          "" => "true"
  size:                 "" => "s-2vcpu-4gb"
  ssh_keys.#:           "" => "1"
  ssh_keys.0:           "" => "21941588"
  status:               "" => "<computed>"
  vcpus:                "" => "<computed>"
digitalocean_droplet.database: Still creating... (10s elapsed)
digitalocean_droplet.database: Still creating... (20s elapsed)
digitalocean_droplet.database: Still creating... (30s elapsed)
digitalocean_droplet.database: Provisioning with 'local-exec'...
digitalocean_droplet.database (local-exec): Executing: ["/bin/sh" "-c" "sleep 100\nANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u root --private-key ~/.ssh/workshout-do -i '206.XXX.XXX.XXX,' ansible/database.yml\n"]
digitalocean_droplet.database: Still creating... (40s elapsed)
digitalocean_droplet.database: Still creating... (50s elapsed)
digitalocean_droplet.database: Still creating... (1m0s elapsed)
digitalocean_droplet.database: Still creating... (1m10s elapsed)
digitalocean_droplet.database: Still creating... (1m20s elapsed)
digitalocean_droplet.database: Still creating... (1m30s elapsed)
digitalocean_droplet.database: Still creating... (1m40s elapsed)
digitalocean_droplet.database: Still creating... (1m50s elapsed)
digitalocean_droplet.database: Still creating... (2m0s elapsed)
digitalocean_droplet.database: Still creating... (2m10s elapsed)

### Expected Behavior
local-exec should run after resource has finished being created (as per docs: https://www.terraform.io/docs/provisioners/local-exec.html)

### Actual Behavior
local-exec runs long before droplet has finished being created.

### Steps to Reproduce
`terraform apply`

**Comment by eddiezane** [comment]
@jon-node28 I believe the provisioner running during creation is intended behavior. In case something goes wrong during provisioning the resource will not have been deemed successfully created.

```
digitalocean_droplet.web: Still creating... (10s elapsed)
digitalocean_droplet.web: Still creating... (20s elapsed)
digitalocean_droplet.web: Still creating... (30s elapsed)
digitalocean_droplet.web: Provisioning with 'local-exec'...
digitalocean_droplet.web (local-exec): Executing: ["/bin/sh" "-c" "exit 1"]

Error: Error applying plan:

1 error(s) occurred:

* digitalocean_droplet.web: Error running command 'exit 1': exit status 1. Output:

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Is there an issue you're encountering? Will reopen if so.

**Comment by jon-node28** [comment]
If that's the case then I would say the docs at https://www.terraform.io/docs/provisioners/local-exec.html are misleading. Specifically: "The local-exec provisioner invokes a local executable after a resource is created"

The problem I'm having is that various package related functions were still executing on the remote server at the time local-exec runs. For example the list of packages to upgrade on the Ubuntu was not yet available and I'm sporadically unable to obtain an apt lock.

**Comment by eddiezane** [comment]
Totally see where the confusion is there.

Under the [Provisioner](https://www.terraform.io/docs/provisioners/index.html) top level docs it says

> Provisioners are used to execute scripts on a local or remote machine as part of resource creation or destruction.

and

> Creation-time provisioners are only run during creation, not during updating or any other lifecycle.

Have a look at https://github.com/radekg/terraform-provisioner-ansible. I've had great success with it and it handles all that polling logic automagically.
