### ISSUE TITLE
Module Dependency Errors

### ISSUE THREAD

**Issue by ArtiomL** [terraform-providers/terraform-provider-digitalocean#150]
Hi,

I have an issue with modules using the DigitalOcean provider.

Seems like an `output` variable of one module can't be used as an `input` variable to another module.

### Terraform Version
```
Terraform v0.11.8
+ provider.digitalocean v1.0.2
+ provider.external v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_firewall
- digitalocean_droplet
- digitalocean_ssh_key

This issue appears to affect multiple resources.

### Terraform Configuration Files
```hcl
# DigitalOcean Resources

provider "digitalocean" {}

# Droplet
module "droplet" {
  source          = "./droplet"
  do_region       = "${var.do_region}"
  key_path        = "${var.key_path}"
  key_name        = "${var.key_name}"
  droplet_names   = "${var.droplet_names}"
  droplet_image   = "${var.droplet_image}"
  droplet_size    = "${var.droplet_size}"
  droplet_backups = "${var.droplet_backups}"
  floating_ip     = "${var.floating_ip}"
  user_data       = "${var.user_data}"
  tags_shared     = "${var.tags_shared}"
}

# Public IP
module "ifconfig" {
  source = "github.com/ArtiomL/f5-terraform/modules/common/ifconfig"
}

# Firewall
module "firewall" {
  source        = "./firewall"
  firewall_name = "${var.firewall_name}"
  droplet_ids   = "${module.droplet.ids}"
  tags_shared   = "${var.tags_shared}"
}

```

The main file is here: https://github.com/ArtiomL/terraform-do/blob/master/modules/main.tf

The modules are here: https://github.com/ArtiomL/terraform-do/tree/master/modules

### Debug Output
```
/opt/terraform/terraform-do/modules $ terraform plan

Error: module.firewall.digitalocean_firewall.main: droplet_ids: should be a list

/opt/terraform/terraform-do/modules $ 

```

### Expected Behavior
The `firewall` module should "understand" that some of its input variables depend on previous modules executing and producing their outputs.

### Actual Behavior
Dependency errors.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan` or `terraform apply`

Thanks.

**Comment by andrewsomething** [comment]
Hi, thanks for the report.

Taking a look at the module, it seems that the issue is that it is not presenting the Droplet IDs to the firewall resource as a list here:

https://github.com/ArtiomL/terraform-do/blob/master/modules/firewall/main.tf#L9

Compare that line to this one from the docs:

```
 droplet_ids = ["${digitalocean_droplet.web.id}"]
```

**Comment by andrewsomething** [comment]
The list of Droplet IDs is being presented to the firewall resource as a string, not a list. On line 9 of `modules/firewall/main.tf`, change:

     droplet_ids = "${var.droplet_ids}"

to:

      droplet_ids = ["${var.droplet_ids}"]

and it will work as expected.

```
diff --git a/modules/firewall/main.tf b/modules/firewall/main.tf
index d76f7dd..bef0644 100644
--- a/modules/firewall/main.tf
+++ b/modules/firewall/main.tf
@@ -6,7 +6,7 @@ locals {
 
 resource "digitalocean_firewall" "main" {
   name        = "${var.firewall_name}"
-  droplet_ids = "${var.droplet_ids}"
+  droplet_ids = ["${var.droplet_ids}"]
 
   inbound_rule = [
     {
```

**Comment by ArtiomL** [comment]
That's strange, because `var.droplet_ids` is already a list.

The `droplet` module output is a list, which is what I pass to the `firewall` module:
https://github.com/ArtiomL/terraform-do/blob/master/modules/droplet/outputs.tf#L4

Referencing a variable this way should return a list:
https://www.terraform.io/docs/configuration/interpolation.html#user-list-variables

**Comment by eddiezane** [comment]
@ArtiomL Andrew and I are at HashiConf next week and will talk to the Terraform team about expected behavior with this one.

**Comment by eddiezane** [comment]
Thanks a ton for clarifying, @nicholasjackson. You're the best!
