### ISSUE TITLE
RFE: Get latest image for distribution

### ISSUE THREAD

**Issue by ArtiomL** [terraform-providers/terraform-provider-digitalocean#153]
Hi,

Please consider adding a data source that could output the latest image slug for a specific distribution.

For example:
Input: `Debian`
Output: `debian-9-x64`

Thanks.

**Comment by eddiezane** [comment]
Thanks for the request. I can totally see the use case for this one already (I always have trouble remembering the slugs).

It might be possible to hack something together with https://developers.digitalocean.com/documentation/v2/#list-all-distribution-images but I this would be better implemented at the DO API level. Would you please make a feature request at https://ideas.digitalocean.com?

Will close this issue for the time being.

**Comment by ArtiomL** [comment]
Sure, thanks!

> It might be possible to hack something...

That is exactly what I'm doing, but it's really a "*dirty* hack":
😄 

```
variable "image_dist" {
  description = "Image distribution"
  default     = "Debian"
}

variable "image_url" {
  description = "API URL"
  default     = "https://api.digitalocean.com/v2/images?per_page=999&type=distribution"
}

data "external" "image" {
  program = ["sh", "-c", "curl -sSL '${var.image_url}' -H 'Authorization: Bearer ${var.do_token}' | jq --arg image_dist ${var.image_dist} '.images[] | select(.distribution == $image_dist and (.description | startswith($image_dist)) and .public == true)' | jq -s -c 'sort_by(.description) | .[-1]' | jq '{slug: .slug}'"]
}

output "image" {
  value = "${data.external.image.result.slug}"
}

variable "do_token" {
  description = "DigitalOcean personal access token"
  default     = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
}

```

Cheers.
