### ISSUE TITLE
Feature request: Extend the DigitalOcean provider to include the hosted Kubernetes

### ISSUE THREAD

**Issue by mmisztal1980** [terraform-providers/terraform-provider-digitalocean#155]
### Current Terraform Version
N/A

### Use-cases
V. easy provisioning of a k8s cluster running on the DigitalOcean platform.

### Proposal
It'd be v. nice to have the DigitalOcean provider include support for the DigitalOcean-hosted Kubernetes solution.

### References
https://www.digitalocean.com/products/kubernetes/

**Comment by lfarnell** [comment]
This is really just a matter of waiting for k8's to become GA on DigitalOcean before its included in all the tooling.

**Comment by eddiezane** [comment]
To echo @lfarnell, definitely something we want to deliver! Well get this in when DO K8s hits GA and support lands in https://github.com/digitalocean/godo.

**Comment by mmisztal1980** [comment]
The service is publically available https://blog.digitalocean.com/digitalocean-releases-k8s-as-a-service/

**Comment by aries1980** [comment]
I see it coming, as Kubernetes features released with Godo:

> [v1.7.2] - 2018-12-04
>     #192 Exposes more options for Kubernetes clusters.
> [v1.7.1] - 2018-11-27
>     #190 Expose constants for the state of Kubernetes clusters.
> [v1.7.0] - 2018-11-13
>     #188 Kubernetes support [beta] - @aybabtme

**Comment by andrewsomething** [comment]
:tada: ￼ This was release today in version 1.1.0. You can find the docs here:

https://www.terraform.io/docs/providers/do/r/kubernetes_cluster.html
