### ISSUE TITLE
Certificate and Private Key Stored in State

### ISSUE THREAD

**Issue by acleon** [terraform-providers/terraform-provider-digitalocean#156]
### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

- digitalocean_certificate

### Terraform Configuration Files
```hcl
resource "digitalocean_certificate" "mycertificate" {
  name              = "My Certificate"
  type              = "custom"
  private_key       = "${file("./certs/mycertificate.key")}"
  leaf_certificate  = "${file("./certs/mycertificate.pem")}"
  certificate_chain = "${file("./certs/mycertificate.chain.pem")}"
}
```

### Question

When creating a certificate resource, everything in the resource is stored in the state file, including the private key and the certificate itself. It seems strange because as far as I can tell, there's no need to ever retrieve these details again. Digital Ocean doesn't make them available via their API, so they can't be compared against the state, and Digital Ocean rejects any attempt to create a new resource with the same fingerprint or the same name. Is there a mechanism in Terraform to ignore resource properties when writing to state?

**Comment by aymanrady** [comment]
The state is compared against the provided values ( `./certs/mycertificate.pem` in your case ) to determine if the resource needs to be recreated.

**Comment by andrewsomething** [comment]
This definitely seems like a reasonable request. If someone wanted to tackle this, take a look at how we are handling `user_data` for the Droplet resource using the `HashString` function.
