### ISSUE TITLE
digitalocean_firewall throws "required field is not set" for "protocol" when it is set

### ISSUE THREAD

**Issue by jakubgs** [terraform-providers/terraform-provider-digitalocean#158]
### Terraform Version
```
> terraform --version
Terraform v0.11.9
+ provider.digitalocean v1.0.2
+ provider.null v1.0.0
```
### Affected Resource
Please list the resources as a list, for example:
- `digitalocean_firewall`

### Terraform Configuration Files
```hcl
locals {
  open_ports = ["22", "655", "8000", "8301"]
}

resource "null_resource" "open_ports" {
  count = "${length(local.open_ports)}"
  triggers {
    protocol   = "tcp"
    port_range = "${element(local.open_ports, count.index)}"
  }
}

resource "digitalocean_firewall" "host" {
  name        = "some-firewall-rule"
  droplet_ids = ["${digitalocean_droplet.host.*.id}"]
  inbound_rule = ["${null_resource.open_ports.*.triggers}"]
}
```

### Debug Output
[tf_clean.log](https://github.com/terraform-providers/terraform-provider-digitalocean/files/2511428/tf_clean.log)

### Expected Behavior
When using version before `1.0.2` I was able to use the `null_resource` in order to dynamically generate the `inbound_rule` section from a list of ports that should be open.

### Actual Behavior
Now this approach fails with:
```
Error: module.canary.digitalocean_firewall.host: "inbound_rule.0.protocol": required field is not set
```

### Steps to Reproduce
Just try to `apply` the setup I posted.

**Comment by jakubgs** [comment]
When I inspect the `null_resource` object I see that the structure clearly has the `protocol` attribute set:
```
> terraform show
...
module.canary.null_resource.open_ports.0:
  id = 7779321125867312987
  triggers.% = 2
  triggers.port_range = 22
  triggers.protocol = tcp
module.canary.null_resource.open_ports.1:
  id = 7343218660642232180
  triggers.% = 2
  triggers.port_range = 655
  triggers.protocol = tcp
module.canary.null_resource.open_ports.2:
  id = 5397873754601694444
  triggers.% = 2
  triggers.port_range = 8000
  triggers.protocol = tcp
module.canary.null_resource.open_ports.3:
  id = 7040696997854394024
  triggers.% = 2
  triggers.port_range = 8301
  triggers.protocol = tcp
...
```

**Comment by thefossedog** [comment]
Hey @jakubgs I was intrigued by this - I can't see anything that would have changed in v1.0.0 that would have affected this and to me it looks like more of a terraform issue than 

Haven't had much to do with null resources but it looks like its not returning the object as expected. 

If it worked previously maybe there was an update to  Godo (although again I couldnt see one) or did you change your version of Terraform?

A work around would be to just specify the whole objects

```hcl
variable "inbound_rules" {
default = [
    {
    protocol   = "tcp",
    port_range = "22",
    },
    {
    protocol   = "tcp",
    port_range = "655",
    },    
]  
}
```

**Comment by jakubgs** [comment]
Yeah, that's a horrible workaround that breaks my current workflow.
I'm using `0.11.10` and your module version `0.1.3` and everything works fine. Only when I upgrade to `1.0.0` do I see the `"inbound_rule.0.protocol": required field is not set` error. So as far as I can tell the change that broke this was in `1.0.0`.

**Comment by thefossedog** [comment]
Hey @jakubgs yeah that was the clue I needed.
This PR fixes it, you can pull and build your own version of the provider until the PR is approved (or rejected :(  )
Hope it helps

**Comment by jakubgs** [comment]
Nice, thanks man, appreciate it!

**Comment by andrewsomething** [comment]
This sounds very similar to the issue described here: https://github.com/hashicorp/terraform/issues/16582#issuecomment-342570913

> Assigning values to nested blocks is not supported, but appears to work in certain cases due to a number of coincidences in how Terraform represents values internally. To be more specific: it uses the Go `map[string]interface{}` values for a number of different purposes, and so in some cases it's possible to confuse Terraform into misinterpreting a map created for one purpose as one for another purpose, as you did here, but this will not work robustly due to different expectations about the contents of those maps in different scenarios.
>
> So in fact, unfortunately, the bug here is that what you did ever worked at all, rather than that it failed once you added a data interpolation into the mix confounded. I expect it failed because by doing so this caused Terraform to see the whole list as `<computed>` during validation, but since it's not supposed to be possible to assign values to nested blocks there is no handling of `<computed>` there and so it fails in this strange way.

So while not supported, this happened to work in the previous version of the provider. When the validation was added, it exposed this issue.

**Comment by thefossedog** [comment]
While I was looking at this last I knew somewhere in my head that I had run into something similar before.  Hence my apprehensive comment that I wasn't sure why it worked. 
Could possibly look at extending the GODO sdk to handle it

**Comment by jakubgs** [comment]
I really can't wait for `0.12` to land. Because currently it's extremely difficult to do things that I'm doing. For example I'm passing a list of ports to open to a module that handles my Digital Ocean hosts. That array is then turned via the `null_resource` into a list of maps that can be used with the `digitalocean_firewall` resource in a dynamic way.

If I can't dynamically turn a list of ports into an input into `digitalocean_firewall` then my whole workflow of modules dedicated to different cloud providers is broken, because I can't pass ports I want to open to the modules as variables.

Maybe I'm doing it wrong using the `null_resource`, but as far as I can tell there is no other way in `pre-0.12` Terraform to turn an array into an array of maps.

**Comment by thefossedog** [comment]
Hey @jakubgs If you read @andrewsomething post above you'll see that the fix I have suggested is not an adequate fix.  So that PR won't be in the next release.  Looks like for now you will need to revert to previous version of the provider or provide a map to the resource.

**Comment by jakubgs** [comment]
Yeah, I get that my dude. I was just pointing out that this problem should go away once the new syntax arrives with `0.12`.

**Comment by andrewsomething** [comment]
With 0.12 out the door for sometime now, I'm going to close this one out. Sorry for the problems it created.

For reference, here's one way to acomplish this with the new syntax:

```
locals {
    open_ports = ["22", "655", "8000", "8301"]
}

resource "digitalocean_firewall" "host" {
  name        = "some-firewall-rule"
  droplet_ids = digitalocean_droplet.host.*.id

  dynamic "inbound_rule" {
    for_each = local.open_ports
    content {
      port_range = inbound_rule.value
      protocol   = "tcp"
    }
  }
}
```
