### ISSUE TITLE
SSH Keys not attached to droplet on creation despite SSH keys being uploaded 

### ISSUE THREAD

**Issue by programingnotes** [terraform-providers/terraform-provider-digitalocean#159]
Hello, 

Given `main.tf` with below setup:

```
resource "digitalocean_ssh_key" "root" {
  name       = "root" 
  public_key = "${chomp(file(var.root))}"
}

resource "digitalocean_droplet" "machine" {
  name                = "${var.name}"
  region              = "${var.region}"
  size                = "${var.size}"
  image               = "${var.image}" 
  ssh_keys            = ["${digitalocean_ssh_key.root.fingerprint}"] 
}
```

### Terraform Version
```
// ♥ terraform -v
Terraform v0.11.10
+ provider.digitalocean v1.0.2
```

### Affected Resource(s) 
```
- digitalocean_ssh_key 
- digitalocean_droplet
```

### Expected Behavior
- no password password when `ssh -i path/to/private/key root@droplet_ip` is run 
- no email with root ssh password should be sent

### Actual Behavior
- password prompt is displayed when `ssh -i path/to/private/key root@droplet_ip` is run. 
- email with ssh root password 

### References
- digging around the internets reveals that [the DigitalOcean API does not return the SSH keys initially added to the Droplet at create time as part of the Droplet resource nor can SSH keys be added to or removed from an existing Droplet via the DigitalOcean API. My initial feeling is that this should be documented as a known limitation.] (https://github.com/terraform-providers/terraform-provider-digitalocean/issues/76#issuecomment-394529120).  
- not only should this limitation be documented but also how to address this limitation also should be documented

**Comment by programingnotes** [comment]
Ugh! Closing because this was a configuration mistake on my part.

**Comment by mkeen** [comment]
@programingnotes What was your config mistake? I am dealing with a similar issue and to me, everything looks fine in your initial code example you shared. What was wrong with it?
