### ISSUE TITLE
digitalocean_certificate not working with computed values

### ISSUE THREAD

**Issue by eb08a167** [terraform-providers/terraform-provider-digitalocean#163]
### Terraform Version
Terraform v0.11.10
+ provider.acme v1.0.1
+ provider.digitalocean v1.0.2
+ provider.tls v1.2.0

### Affected Resource(s)
+ digitalocean_certificate

### Terraform Configuration Files
```hcl
resource "tls_private_key" "acme" {
  algorithm = "RSA"
}

resource "acme_registration" "primary" {
  account_key_pem = "${tls_private_key.acme.private_key_pem}"
  email_address   = "${var.acme_email_address}"
}

resource "acme_certificate" "primary" {
  account_key_pem = "${acme_registration.primary.account_key_pem}"
  common_name     = "*.${digitalocean_domain.primary.name}"

  dns_challenge {
    provider = "digitalocean"

    config {
      DO_AUTH_TOKEN = "${var.do_token}"
    }
  }
}

resource "digitalocean_certificate" "primary" {
  name              = "primary-certificate"
  private_key       = "${acme_certificate.primary.private_key_pem}"
  leaf_certificate  = "${acme_certificate.primary.certificate_pem}"
  certificate_chain = "${acme_certificate.primary.issuer_pem}"
}
```

### Debug Output

https://pastebin.com/gWH0iM0q

### Expected Behavior

digitalocean_certificate is created on apply

### Actual Behavior

Terraform fails with ```* digitalocean_certificate.primary: `private_key` is required for when type is `custom` or empty``` error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It's possible to workaround the problem by performing the steps below:

1. Comment the `digitalocean_certificate` resource
2. Run `terraform apply`
3. Uncomment the `digitalocean_certificate` resource
4. Run `terraform apply`

After that the `digitalocean_certificate` resource is successfully created.

**Comment by parruda** [comment]
I can confirm. Having the exact same problem here.

**Comment by maxwedwards** [comment]
Is this not more likely to be the acme_certificate resource not providing the private key after a create and not a problem with the digital ocean provider? Have you tried an example without acme_certificate to eliminate it?

**Comment by etienne-napoleone** [comment]
Same problem here:
```terraform
provider "acme" {
  server_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
}

resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = "${tls_private_key.private_key.private_key_pem}"
  email_address   = "${var.cloudflare_email}"
}

resource "acme_certificate" "certificate" {
  account_key_pem = "${acme_registration.reg.account_key_pem}"
  common_name     = "${var.fqdn}"

  dns_challenge {
    provider           = "cloudflare"

    config {
      CLOUDFLARE_EMAIL   = "${var.cloudflare_email}"
      CLOUDFLARE_API_KEY = "${var.cloudflare_api_key}"  
    }
  }
}

resource "digitalocean_certificate" "cert" {
  name             = "${var.name}"
  private_key      = "${acme_certificate.certificate.private_key_pem}"
  leaf_certificate = "${acme_certificate.certificate.certificate_pem}"

  # depends_on = ["acme_certificate.certificate"]
}
```
I'll get 
```
Error: Error running plan: 1 error(s) occurred:

* module.dns.digitalocean_certificate.cert: 1 error(s) occurred:

* module.dns.digitalocean_certificate.cert: `private_key` is required for when type is `custom` or empty
```

But if I run it without the `digitalocean_certificate` first, then add it: it will work without problem.
