### ISSUE TITLE
Droplet resource removes attached volumes

### ISSUE THREAD

**Issue by justinbarrick** [terraform-providers/terraform-provider-digitalocean#165]
If a droplet resource has volumes attached to it that are managed outside of Terraform (in my use-case, my droplet has volumes attached by the [csi-digitalocean](https://github.com/digitalocean/csi-digitalocean)), then terraform will remove the volumes on next apply:

```
11:18:18  == terraform-deploy => module.kubernetes.digitalocean_droplet.kubernetes_nodes[3]: Modifying... (ID: 119197558)
11:18:18  == terraform-deploy =>   volume_ids.#:          "2" => "1"
11:18:18  == terraform-deploy =>   volume_ids.1419980023: "48b29148-e85c-11e8-a1d1-0a58ac14e059" => ""
11:18:18  == terraform-deploy =>   volume_ids.604109777:  "7eb4efce-e838-11e8-a1d1-0a58ac14e059" => "7eb4efce-e838-11e8-a1d1-0a58ac14e059"
```

Is there any workaround for this issue?

**Comment by andrewsomething** [comment]
If they are being managed outside of Terraform, I think that setting `ignore_changes` for the `volume_ids` attribute is probably the best way to go.
```
resource "digitalocean_droplet" "web" {
  image  = "ubuntu-18-04-x64"
  name   = "web-1"
  region = "nyc2"
  size   = "s-1vcpu-1gb"

  lifecycle {
      ignore_changes = ["volume_ids"]
  }
}
```
See: https://www.terraform.io/docs/configuration/resources.html#ignore_changes

If you also have volumes that you are managing directly w/ Terraform, you can still use the `digitalocean_volume_attachment` resource.

**Comment by justinbarrick** [comment]
Cool! Thanks!
