### ISSUE TITLE
digitalocean_kubernetes

### ISSUE THREAD

**Issue by benjamin-maynard** [terraform-providers/terraform-provider-digitalocean#167]
Hi,

Is it possible to get support for creating Digital Ocean Kubernetes Clusters?

**Comment by maxwedwards** [comment]
I could have a stab at this but I'd probably need a fair bit of oversight to get it over the line.

**Comment by andrewsomething** [comment]
There is some work in-progress here. Hoping we'll see a PR very soon. :tada:

**Comment by mmisztal1980** [comment]
The service is publically available https://blog.digitalocean.com/digitalocean-releases-k8s-as-a-service/

**Comment by andrewsomething** [comment]
:tada: This was release today in version 1.1.0. You can find the docs here:

https://www.terraform.io/docs/providers/do/r/kubernetes_cluster.html

**Comment by andrewsomething** [comment]
@lucasyvas Yes. That's not handled by Terraform itself, but the DigitalOcean Kubernetes service should handle draining the node before it is destroyed.
