### ISSUE TITLE
Fix broken link in github header

### ISSUE THREAD

**Issue by kwent** [terraform-providers/terraform-provider-digitalocean#170]
<img width="564" alt="screen shot 2018-12-05 at 6 01 48 pm" src="https://user-images.githubusercontent.com/879780/49556268-e2a57d00-f8b7-11e8-9179-851e350c6909.png">

Change 

- https://www.terraform.io/docs/providers/digitalocean/
to
- https://www.terraform.io/docs/providers/do/

**Comment by andrewsomething** [comment]
Thanks for pointing this out. Something a bit strange is going on here. :thinking: This has been fixed before, but keeps regressing. I've asked the HashiCorp team who own the terraform-providers org to take a look. I suspect the repos themselves are managed via Terraform and that it is overwriting the manual fix.

**Comment by andrewsomething** [comment]
The correct link is now there, and I've been told that the config has now been updated to match. Thanks again for catching that!
