### ISSUE TITLE
digitalocean_droplet: ipv6_address_private doesn't exist

### ISSUE THREAD

**Issue by pysysops** [terraform-providers/terraform-provider-digitalocean#181]
Good day!

Thanks for this fantastic provider! I'm currently in the process of creating some DigitalOcean modules and have potentially found a bug with `private_networking` and `ipv6`.

### Terraform Version
Terraform v0.11.11
+ provider.digitalocean v1.1.0

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
Example:
```hcl

resource "digitalocean_droplet" "droplet" {
  count = 1

  image = "<< image_id >>"
  name  = "droplet"

  region = "ams3"
  size   = "s-1vcpu-1gb"

  ipv6               = true
  private_networking = true
}

resource "digitalocean_record" "private_aaaa" {
  count = 1

  domain = "example.com"
  type   = "AAAA"
  name   = "${element(digitalocean_droplet.droplet.*.name, count.index)}"
  value  = "${element(digitalocean_droplet.droplet.*.ipv6_address_private, count.index)}"
}

```

### Debug Output
```
* digitalocean_record.private_aaaa.0: Failed to create record: POST https://api.digitalocean.com/v2/domains/private.stg.ghostfoundation.org/records: 422 Data can't be blank and IP address did not match IPv6 format (e.g. 2001:db8::ff00:42:8329).
* module.apps.module.droplets.digitalocean_record.private_aaaa[0]: 1 error(s) occurred:
```

### Expected Behavior
I'm not sure if DigitalOcean have supported IPv6 private networking and removed it, removed it from the API or never supported it?

The documentation here: [digitalocean_droplet](https://www.terraform.io/docs/providers/do/r/droplet.html#ipv6_address_private) suggests that it the provider supports private IPv6 addresses 🤔 

### Actual Behavior
No private IPv6 addresses available from the API or visible in the DigitalOcean dashboard.

**Comment by andrewsomething** [comment]
DigitalOcean has never supported IPv6 private networking. Though it looks like this attribute has been in the code base going almost all the way to the beginning, pre-dating my involvement with the project: https://github.com/hashicorp/terraform/commit/872acb3740684bbc75899ad21e5bae0219920be0

**Comment by pysysops** [comment]
I had a suspicion that may have been the case. Thanks for the quick update and clarification @andrewsomething 😄

**Comment by stack72** [comment]
@andrewsomething is this correct? I see IPv6 related code in the godo SDK

this is why this is able to happen:

```
func findIPv6AddrByType(d *godo.Droplet, addrType string) string {
	for _, addr := range d.Networks.V6 {
		if addr.Type == addrType {
			if ip := net.ParseIP(addr.IPAddress); ip != nil {
				return strings.ToLower(addr.IPAddress)
			}
		}
	}
	return ""
}
```

**Comment by andrewsomething** [comment]
DigitalOcean does offer public IPv6 for Droplets, but not on the private network.

godo's `NetworkV6` struct does have a `Type` field, but as of today that will always be `public`

https://github.com/digitalocean/godo/blob/ff6039cb012353bb30f0ad9f16517fb3467c533c/droplets.go#L271-L277

`Droplet` also has `PrivateIPv4()`, `PublicIPv4()`, and `PublicIPv6()` methods, but no corresponding  `PrivateIPv6()` one.

https://github.com/digitalocean/godo/blob/ff6039cb012353bb30f0ad9f16517fb3467c533c/droplets.go#L66-L109

**Comment by stack72** [comment]
ah @andrewsomething,

do you want me to send a PR that deprecates it? I never realised that you can't do private IPv6 and private together

Paul
