### ISSUE TITLE
Kubernetes node_pool tags constantly update

### ISSUE THREAD

**Issue by troywilson** [terraform-providers/terraform-provider-digitalocean#184]
### Terraform Version
terraform v0.11.11
digitalocean v1.1.0

### Affected Resource(s)
digitalocean_tag
digitalocean_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "digitalocean_tag" "test" {
  name = "test"
}

resource "digitalocean_kubernetes_cluster" "test" {
  name = "test"
  region = "nyc1"
  version = "1.13.1-do.2"
  tags = ["${digitalocean_tag.test.name}"]

  node_pool {
    name = "test-pool"
    size = "s-2vcpu-2gb"
    node_count = 3
    tags = ["${digitalocean_tag.test.name}"]
  }
}
```

### Debug Output
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ digitalocean_kubernetes_cluster.test
      node_pool.0.tags.#:          "0" => "1"
      node_pool.0.tags.<tag_id>: "" => "test"

Plan: 0 to add, 1 to change, 0 to destroy.

### Expected Behavior
Tag is applied once.

### Actual Behavior
Tag is applied every time.

### Steps to Reproduce
1. `terraform apply`

**Comment by troywilson** [comment]
Resource digitalocean_kubernetes_node_pool exhibits the same behaviour.

**Comment by lfarnell** [comment]
@troywilson I wonder if adding a lifecycle block to ignore tag changes would work for you
```hcl
lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      tags,
    ]
  }
```

**Comment by andrewsomething** [comment]
Wanted to provide a quick update here. I have a branch that will resolve this issue, but it exposed that there is an underlying problem with the DigitalOcean API. It is handling node pool tags inconsistently.

When a node pool is created in the same request as the cluster itself, tags from the parent cluster are not automatically apply to the children node pools. This is the currently documented behaviour. When a new node pool is created independently from the cluster, cluster level tags are automatically applied to the node pool. This is not the intended behaviour.

So fixing this issue on one side just introduces it on the other. I've flagged this with the DigitalOcean Kubernetes team. Once fixed there, we'll have a fix for the provider ready to go.
