### ISSUE TITLE
`private_networking = true` crashes Terraform in already existing droplet

### ISSUE THREAD

**Issue by MarianoRD** [terraform-providers/terraform-provider-digitalocean#191]
### Terraform Version
Terraform v0.11.11
* provider.digitalocean v1.1.0

### Affected Resource(s)
* digitalocean_droplet

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "digitalocean_droplet" "test" {
  name               = "test"
  size               = "${var.droplet_size}"
  image              = "${var.do_image}"
  region             = "${var.do_region}"
  ipv6               = false
  private_networking = true
  monitoring         = true
  ssh_keys           = "${var.ssh_keys}"
}
```

### Debug Output
https://gist.github.com/MarianoRD/15c15e2c1400f0f18b0489f9c3ab5b5c

### Expected Behavior
Terraform should know how to habilitate the Private Networking, either by requesting a new resource or by being able to power cycle the Droplet.

### Actual Behavior
The Private Networking IP is not requested and a 403 error is thrown from the API

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Droplet with `private_networking: false`
2. Change the `.tf` configuration to `private_networking: true`
3. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #67

**Comment by andrewsomething** [comment]
As this is a 403 error, is it possible that you are using a read-only API token here? The only way I have been able to reproduce this error with v1.1.0 of the provider is to use a read-only token, and in that case, that is the expected response. With a write token, I am able to enable private networking successfully:

```
$ terraform apply
digitalocean_droplet.test: Refreshing state... (ID: 135104128)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ digitalocean_droplet.test
      private_networking: "false" => "true"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

digitalocean_droplet.test: Modifying... (ID: 135104128)
  private_networking: "false" => "true"
digitalocean_droplet.test: Still modifying... (ID: 135104128, 10s elapsed)
digitalocean_droplet.test: Modifications complete after 12s (ID: 135104128)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Is there any additional information that you can provide about how you hit this issue? Was the Droplet an existing resource imported into Terraform?

**Comment by MarianoRD** [comment]
I think you're right and I messed up the API Keys, using the write only one to run the Terraform script.

**Comment by andrewsomething** [comment]
Great. Feel free to reopen if you run into it again.
