### ISSUE TITLE
Installing latest version of DO Provider

### ISSUE THREAD

**Issue by proffalken** [terraform-providers/terraform-provider-digitalocean#197]
Hey folks,

Not so much a bug as a request - I'm trying to implement the DO Spaces stuff that I can see has been merged, however it isn't supported in the latest version of the TF provider available from Hashicorp:

```
Error: digitalocean_spaces_bucket.packer-images: Provider doesn't support resource: digitalocean_spaces_bucket


Error: provider.digitalocean: : invalid or unknown key: spaces_access_id



Error: provider.digitalocean: : invalid or unknown key: spaces_secret_key
```

Is the update at releases.hashicorp.com an issue for Hashicorp to resolve, or can I install an updated version of the plugin from elsewhere?

**Comment by lfarnell** [comment]
@proffalken The problem you are hitting is that the spaces resource exists in master but hasn't been released yet through releases.hashicorp.com yet. If you wanted to uses the spaces resource you would have to build from source at the moment or you can use the [0.12 snapshot build](http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/terraform-provider-digitalocean/1.2.0-dev20190216H00-dev/) but following the instructions [here](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins). I tested this with Terraform 0.11.13. That can get you up and running until a new release is cut.

**Comment by proffalken** [comment]
Fantastic, thanks.

I don't suppose there is an ETA for the release by Hashicorp?

**Comment by andrewsomething** [comment]
v1.12.0 was just released. In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#120-april-23-2019
