### ISSUE TITLE
Implement CDN Endpoint Resource

### ISSUE THREAD

**Issue by trentrosenbaum** [terraform-providers/terraform-provider-digitalocean#204]
#### Description

This issue covers the introduction of the CDN endpoint resource into the digitalocean terraform provider.
After PRs relating to this issue are merged, the provider will allow a developer to provision a
CDN in front of a digitalocean space.  The developer should expect to be able to adjust attributes
relating to ttl and the use of a customer domain.

This new resources will be implemented using to godo library that is a client to the
digitalocean v2 API:
* https://developers.digitalocean.com/documentation/v2
This issue will focus on the CDN Endpoints section of the documentation:
* https://developers.digitalocean.com/documentation/v2/#cdn-endpoints

#### Proposed Terraform Structure

```
resource "digitalocean_cdn" "foobar" {
  origin = "${digitalocean_spaces_bucket.bucket.bucket_domain_name}"
}
```

or

```
resource "digitalocean_cdn" "foobar" {
  origin = "${digitalocean_spaces_bucket.bucket.bucket_domain_name}"
  ttl = 1800
}
```

or

```
resource "digitalocean_cdn" "foobar" {
  origin = "${digitalocean_spaces_bucket.bucket.bucket_domain_name}"
  custom_domain = "${digitalocean_record.foo.fqdn}"
  certificate_id = "${digitalocean_certificate.foo.id}"
}
```

or

```
resource "digitalocean_cdn" "foobar" {
  origin = "${digitalocean_spaces_bucket.bucket.bucket_domain_name}"
  custom_domain = "${digitalocean_record.foo.fqdn}"
  certificate_id = "${digitalocean_certificate.foo.id}"
  ttl = 1800
}
```

#### Validation of CDN attributes

The only documented required field is "origin" and this will be set in the schema.
Next we have optional fields and this include "custom_domain" and the "certificate_id".
These will be validate before the resource is created and updated and fail if either is present without the other.

The CDN endpoints API mentions the TTL default is 3600 seconds, (1 hour).  Validation will make sure it is at least 1 second.
This TTL validation is present on the existing records resource, (resource_digitalocean_record.go)

#### Proposed Tasks
- [] Update digitalocean/provider.go to expose new resource.
- [] Define schema to represent the previous proposed terraform structures.
- [] Create digitalocean/resource_digitalocean_cdn.go and digitalocean/resource_digitalocean_cdn_test.go
- [] Update website documentation to explain the use of CDN resource within provider.

**Comment by andrewsomething** [comment]
:+1: Sounds good @trentrosenbaum. Thanks for the detailed write up.

**Comment by andrewsomething** [comment]
Closed via https://github.com/terraform-providers/terraform-provider-digitalocean/pull/219
