### ISSUE TITLE
Implement the Project Resource

### ISSUE THREAD

**Issue by trentrosenbaum** [terraform-providers/terraform-provider-digitalocean#207]
#### Description

This issue covers the introduction of the Project resource into the DigitalOcean terraform provider.
After PRs relating to this issue are merged, the provider will allow a developer to provision a
Project.  The developer should expect to be able to adjust attributes
relating to Project and associate a subset of DigitalOcean resources with the project.

This new resources will be implemented using to godo library that is a client to the
digitalocean v2 API:
* https://developers.digitalocean.com/documentation/v2
This issue will focus on the Projects section of the documentation:
* https://developers.digitalocean.com/documentation/v2/#projects
* https://developers.digitalocean.com/documentation/v2/#project-resources

#### Proposed Terraform Structure

```
resource "digitalocean_project" "api" {
  name = "my-web-api"
  description = ""
  purpose = ""
  environment = "development"
  resources = [
    "${digitalocean_volume.foo.urn}"
    "${digitalocean_spaces_bucket.foo.urn}"
    "${digitalocean_droplet.foo.urn}"
  ]
}
```

#### Validation of CDN attributes
The following validations are being placed on the fields.
1. name - required; cannot be zero; length of 1 - 175 characters.
2. description - Optional; default ""; length of 0 - 255 characters.
3. purpose - Optional; default "Web Application"; length of 0 -255 characters.
4. environment - Optional; default "Development"; restricted to Development, Staging, Production
5. resources - Optional.

#### Assumptions

1. The use of a default project is to be able to assign resources to it automatically.  This would create too much drift if the project is provisioned through Terraform and as a result, the "is_default" attribute will be assigned "false" and a user will not be able to set it through terraform.
2. The console allows a name change at the project level and this does not create a new resource.  The terraform will not create a new project if the name changes.
3. When a project is removed from the account then the project resources, (the relationship itself) is removed and the individual resources are automatically associated with the existing default project.

#### Proposed Tasks
- [] Update the following existing resources to expose a URN attribute, (inc website).
  * [MERGED] Droplet
  * [MERGED] Load Balancer
  * [MERGED ]Domain
  * [MERGED]Volume
  * [MERGED] Floating IP
  * [MERGED] Spaces Bucket
- [] Update digitalocean/provider.go to expose new resource.
- [] Define schema to represent the previous proposed terraform structures.
- [] Create digitalocean/resource_digitalocean_project.go and digitalocean/resource_digitalocean_project_test.go
- [] Update website documentation to explain the use of Project resource within the provider.

**Comment by andrewsomething** [comment]
Closed via https://github.com/terraform-providers/terraform-provider-digitalocean/pull/218
