### ISSUE TITLE
Read-only Database Replica Resource

### ISSUE THREAD

**Issue by andrewsomething** [terraform-providers/terraform-provider-digitalocean#224]
With the addition of support for DigitalOcean Managed Databases, we should extend support for related resources such as read-only replicas.

Proposed format:

```hcl
resource "digitalocean_database_replica" "read-01" {
  cluster_id = "${digitalocean_database.foo.id}"
  name       = "read-replica-01"
  region     = "nyc3"
  size       = "db-s-2vcpu-4gb"
}
```

API: https://developers.digitalocean.com/documentation/v2/#create-a-read-only-replica

Related: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/189

**Comment by Zyqsempai** [comment]
I can take this one!

**Comment by timkrins** [comment]
As a result of my support ticket, the DO API has been updated to return the UUID of the replica (keyed in the `/replicas`  response under `{"replicas":[{"id" ...`).
Will create new issue now that the API is available.
