### ISSUE TITLE
The plugin is incompatible with terraform 0.12

### ISSUE THREAD

**Issue by jackivanov** [terraform-providers/terraform-provider-digitalocean#229]
### Terraform Version
```
$ ./terraform -v
Terraform v0.12.0-rc1
+ provider.digitalocean v1.2.0
```

### Affected Resource(s)
- All digitalocean resources

### Terraform Configuration Files
```hcl
resource "digitalocean_floating_ip" "main" {
  region     = "fra1"
}
```

### Expected Behavior
The plugin runs 

### Actual Behavior
The plugin fails

**Error: Failed to instantiate provider "digitalocean" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]**

### Steps to Reproduce
1. Run `terraform apply` using terraform 0.12.0-rc1 or 0.12.0-beta2

### References

- Seems a duplicate of #179, but as Terraform 0.12 support added in https://github.com/terraform-providers/terraform-provider-digitalocean/commit/bac42449500fa66ce4df7a103bbfa985dfdd9293 it should be considered as a bug now

**Comment by andrewsomething** [comment]
The new 1.3.0 build should now be available via `terraform init -upgrade`

**Comment by drweber** [comment]
> The new 1.3.0 build should now be available via `terraform init -upgrade`

and if this will not help you, as for me was, check your `~/.terraform.d/plugins/` for the old version of plugins and delete them or update manually

cheers :)
