### ISSUE TITLE
terraform import: digitalocean dns record crashes on import 

### ISSUE THREAD

**Issue by samstav** [terraform-providers/terraform-provider-digitalocean#231]
### Terraform Version

```
$ terraform version
Terraform v0.11.13
+ provider.digitalocean v1.2.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_record

### Terraform Configuration Files
```hcl
resource "digitalocean_record" "my_z_sub_record" {
  domain  = "z.example.com"
  name    = "z"
  type    = "NS"
  value   = "BADPLACEHOLDER.NET"
}

```

### Debug Output

https://gist.github.com/samstav/c4878f44241df36efa5c6eb3167ec19d

### Expected Behavior

DNS Record should import to tf state.

### Actual Behavior
Import crashed and did not return any useful error.

```
Error: digitalocean_record.my_z_sub_record (import id: z.example.com,70910975): import digitalocean_record.my_z_sub_record (id: z.example.com,70910975): nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```

### Steps to Reproduce

```
terraform import digitalocean_record.my_z_sub_record z.example.com,70910975
```

------------------------

This might be due to an invalid record ID.

**Comment by eddiezane** [comment]
I'm able to replicate this when providing an invalid record ID.

This is because of this bit right here in the resource read:

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/3dc0ca55ce9f8f9fb0ecf00df73dfe6b24d1bd84/digitalocean/resource_digitalocean_record.go#L189-L194

We're making an old assumption from something else and are ignoring the 404.

@andrewsomething would you happen to know why we were doing that?

**Comment by andrewsomething** [comment]
@eddiezane This is an extremely common pattern. If the read function encounters a 404, the resources ID is set to an empty string which is interpreted as not existing. This creates a diff between the current state and the configuration, so Terraform will attempt to recreate the resource. This pattern is repeated in essential every provider: https://github.com/search?q=org%3Aterraform-providers+not+found%2C+removing+from+state%3A+%25s%22&type=Code

A few thoughts:
- Better logging might have helped here.
- You get a much clearer error message for resources that just use `ImportStatePassthrough`. Will investigate how to make sure we trigger that for ones like this that require a custom importer function.
