### ISSUE TITLE
Importing digitalocean_records appends a . after the value

### ISSUE THREAD

**Issue by JamJar00** [terraform-providers/terraform-provider-digitalocean#233]
### Terraform Version
```
Terraform v0.11.13
+ provider.digitalocean v1.3.0
```

### Affected Resource(s)
- digitalocean_record

### Terraform Configuration Files
(Trimmed down for clarity)
```hcl
resource "digitalocean_domain" "darkriftnetworking_com" {
  name      = "darkriftnetworking.com"
}

...

resource "digitalocean_record" "ns1" {
  domain    = "${digitalocean_domain.darkriftnetworking_com.name}"
  type      = "NS"
  name      = "@"
  value     = "ns1.digitalocean.com"
  ttl       = 1800
}

resource "digitalocean_record" "ns2" {
  domain    = "${digitalocean_domain.darkriftnetworking_com.name}"
  type      = "NS"
  name      = "@"
  value     = "ns2.digitalocean.com"
  ttl       = 1800
}

resource "digitalocean_record" "ns3" {
  domain    = "${digitalocean_domain.darkriftnetworking_com.name}"
  type      = "NS"
  name      = "@"
  value     = "ns3.digitalocean.com"
  ttl       = 1800
}
```

### Debug Output
I presume I will need to rerun the import to show this. Can do on request.

### Expected Behavior
Expected the plan to show no changes on these records.

### Actual Behavior
Plan actually wants to remove `.` character from _some_ of the records imported (most records were fine)
```
  ~ digitalocean_record.ns1
      value:                "ns1.digitalocean.com." => "ns1.digitalocean.com"

  ~ digitalocean_record.ns2
      value:                "ns2.digitalocean.com." => "ns2.digitalocean.com"

  ~ digitalocean_record.ns3
      value:                "ns3.digitalocean.com." => "ns3.digitalocean.com"
```

### Steps to Reproduce
1. Create a new domain with nameserver records
2. Run `terraform import` for the domain and each record
3. `terraform apply`
I have only tried this once so far (took a while to import all my DNS records so not actualy certain if this was a one-off or is reproducible)

### Important Factoids
Terraform state shows the `.`s.
```json
"attributes": {
	"domain": "darkriftnetworking.com",
	"flags": "0",
	"fqdn": "@.darkriftnetworking.com",
	"id": "33609600",
	"name": "@",
	"port": "0",
	"priority": "0",
	"tag": "",
	"ttl": "1800",
	"type": "NS",
	"value": "ns1.digitalocean.com.",
	"weight": "0"
},
```
When removing the `.`s in the Terraform state file and running `terraform refresh` the `.`s reappear (I'll be honest, I'm still new to Terraform so not completely sure on the tfstate file's lifecycle!)

When accessing the DigitalOcean API manually the `.`s are not present:
Retriveing all records shows:
```json
{
	"domain_records": [{
			"id": 33609600,
			"type": "NS",
			"name": "@",
			"data": "ns1.digitalocean.com",
			"priority": null,
			"port": null,
			"ttl": 1800,
			"weight": null,
			"flags": null,
			"tag": null
		}, {
			"id": 33609601,
			"type": "NS",
			"name": "@",
			"data": "ns2.digitalocean.com",
			"priority": null,
			"port": null,
			"ttl": 1800,
			"weight": null,
			"flags": null,
			"tag": null
		}, {
			"id": 33609602,
			"type": "NS",
			"name": "@",
			"data": "ns3.digitalocean.com",
			"priority": null,
			"port": null,
			"ttl": 1800,
			"weight": null,
			"flags": null,
			"tag": null
		},
...
```
Retriving a specific record shows:
```json
{
	"domain_record": {
		"id": 33609602,
		"type": "NS",
		"name": "@",
		"data": "ns3.digitalocean.com",
		"priority": null,
		"port": null,
		"ttl": 1800,
		"weight": null,
		"flags": null,
		"tag": null
	}
}
```
Not all records imported were affected, it appers to be only my `MX` and `NS` records that were corrupted.

**Comment by andrewsomething** [comment]
As far as I understand, Terraform's behaviour is correct here. The dot (`.`) is required. Importing a record with a config similar to yours and allowing `terraform apply` to run will result in a 422 error from the DigitalOcean API: `Data needs to end with a dot (.)`

```
$ terraform apply
digitalocean_record.ns1: Refreshing state... (ID: 64255736)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ digitalocean_record.ns1
      value: "ns1.digitalocean.com." => "ns1.digitalocean.com"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

digitalocean_record.ns1: Modifying... (ID: 64255736)
  value: "ns1.digitalocean.com." => "ns1.digitalocean.com"

Error: Error applying plan:

1 error(s) occurred:

* digitalocean_record.ns1: 1 error(s) occurred:

* digitalocean_record.ns1: Failed to update record: PUT https://api.digitalocean.com/v2/domains/do-test.ml/records/64255736: 422 Data needs to end with a dot (.)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

So the confusing bit is that the DigitalOcean API returns the value without the dot (`.`) despite requiring it to create or update the record.

Perhaps the Terraform provider should hide this from the user? 🤔 We could use a `DiffSuppressFunc` to not show a plan when the dot (`.`) is missing from the config but actually ensure it exists behind the scenes in the state. Though that feels a bit "magical."

**Comment by JamJar00** [comment]
Interesting, I haven't yet been able to run the apply as it would currently change a droplet I can't yet fully recreate

Having worked more with GCloud and Terraform yesterday the same `.` is present on the end of DNS records there so I think perhaps I'm missing the significance of it in the DNS system generally.

I agree it seems strange to require on creation/update but not read, however that's a DigitalOcean quirk so (for what my 2 cents are worth here) I would probably not hide this behaviour behind Terraform. The errors are well documented (as shown) and it would probably be a breaking change for users.

I'm satisfied that this is a lack of my own understanding so if you'd like to close this thaen feel free. Thanks for the swift response.
