### ISSUE TITLE
build from source (make build) failing

### ISSUE THREAD

**Issue by shinenelson** [terraform-providers/terraform-provider-digitalocean#246]
### Terraform Version
Terraform v0.12.1-dev

### Expected Behavior
What should have happened?
`make build` should have completed without any errors

### Actual Behavior
What actually happened?
```
==> Checking that code complies with gofmt requirements...
go install
verifying github.com/hashicorp/terraform@v0.12.0: checksum mismatch
	downloaded: h1:It2vmod2dBMB4+r+aUW2Afx0HlftyUwzNsNH3I2vrJ8=
	go.sum:     h1:B5lTDWSdEbbjxrTZQ8GdsDlH7FnDrIvF42GykbhQ6tA=
GNUmakefile:10: recipe for target 'build' failed
make: *** [build] Error 1
```

### Steps to Reproduce
* `git clone` the repository
* `make build`

### Important Factoids
I'm running `go version go1.12.5 linux/amd64` with `Terraform v0.12.1-dev` (built from `hashicorp/terraform@master`). (Not that the issue is related to the `go` or the `terraform` binaries installed on my system, though).

I suspect that the `go.sum` was missed to be updated after there was a terraform release recently (?)

**Comment by andrewsomething** [comment]
Thanks for the report @shinenelson. To be honest, I'm not entirely sure what the issue is here. It has been building fine in CI as well as locally for me. Though blowing away `go.mod` and regenerating does create this diff:

```
-github.com/hashicorp/terraform v0.12.0 h1:B5lTDWSdEbbjxrTZQ8GdsDlH7FnDrIvF42GykbhQ6tA=
+github.com/hashicorp/terraform v0.12.0 h1:It2vmod2dBMB4+r+aUW2Afx0HlftyUwzNsNH3I2vrJ8=
```

Can you try building from the `issues/246` branch and confirming it resolves the issue for you?

PR with that change: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/250

Perhaps related to: https://github.com/golang/go/issues/29278

**Comment by shinenelson** [comment]
I can confirm that the `issues/246` branch compiles successfully as expected.

You can merge #250. I would've approved the changes directly, but there are some other deletions that I can't vouch for, though I know it is not generated manually-by-hand. However, I also noticed a change in the checksum for https://github.com/hashicorp/go-getter, so, that's another reason why I wouldn't want to approve those changes directly. ( I wish there was a mechanism to approve specific code-snippets in a pull request and then some other reviewer(s) could take a look at the rest of the pull request )

regarding golang/go#29278, I would have to ask you with which version of `go` was the existing `go.sum` generated? Wouldn't it be related only if the `go` version used to generate the file was pre-1.11.4? Though that's highly unlikely since `go 1.11.4` was released a long time ago.

**Comment by jondkelley** [comment]
So whats the work around?
