### ISSUE TITLE
Add tagging support to the digitalocean_database_cluster resource

### ISSUE THREAD

**Issue by rozhok** [terraform-providers/terraform-provider-digitalocean#253]
Hey. I'm unable to tag by database cluster. Is it excepted?

### Terraform Version
```
Terraform v0.12.1
+ provider.aws v2.14.0
+ provider.digitalocean v1.4.0
```
### Affected Resource(s)
- digitalocean_database_cluster
- digitalocean_tag

### Terraform Configuration Files
```hcl
resource "digitalocean_tag" "microservice" {
  name = "backend"
}

resource "digitalocean_database_cluster" "backend-db" {
  name       = "backend-db"
  engine     = "pg"
  version    = "11"
  size       = "db-s-1vcpu-1gb"
  region     = "fra1"
  node_count = 1
  tags = [digitalocean_tag.microservice.id]
}
```

### Debug Output
https://gist.github.com/rozhok/b6e48bf85e6a4fd73005deb0a9ec3e97

### Expected Behavior
Tags should be successfully added to the db cluster.

### Actual Behavior
Tags are not added:
```
Error: Unsupported argument

  on ../config/databases.tf line 12, in resource "digitalocean_database_cluster" "backend-db":
  12:   tags = [digitalocean_tag.microservice.id]

An argument named "tags" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by andrewsomething** [comment]
Thanks for raising this. Tagging support for databases wasn't added to the DigitalOcean API until after the resource made its way into the Terraform provider. We need to add it here as well.

**Comment by lfarnell** [comment]
@andrewsomething it seems that the [documentation](https://developers.digitalocean.com/documentation/v2/#databases) around databases doesn’t have references to tags. I had thought this future wasn’t implemented until I saw this in the UI.

**Comment by Zyqsempai** [comment]
I can take this one, since https://github.com/digitalocean/godo/issues/249 already done!
