### ISSUE TITLE
Databases should return an URN for use with projects

### ISSUE THREAD

**Issue by andrewsomething** [terraform-providers/terraform-provider-digitalocean#256]
Both the `digitalocean_database_cluster` resource and datasource should return a computed `urn` attribute in the form `do:dbaas:<DATABASE_ID>` in order to allow assigning databases to projects.

Blocked on: https://github.com/digitalocean/godo/issues/237

**Comment by stack72** [comment]
Hi @andrewsomething 

I just opened a PR that will fix https://github.com/digitalocean/godo/issues/237

I'd love to get your feedback on that

Paul
