### ISSUE TITLE
Not able to pass multible ssh keys to droplet.

### ISSUE THREAD

**Issue by dpisano** [terraform-providers/terraform-provider-digitalocean#261]
Hi,

It looks like in `digitalocean_droplet` `ssh_keys` was changed from a list to a string in 8a67ab90bb4c2a7a96360197487acf4acdba1192. When you try and send more than one ssh key for a droplet DigitalOcean will send back a 422 error.

### Terraform Version
```
Terraform v0.12.0
+ provider.digitalocean v1.4.0
```

### Affected Resource(s)
Please list the resources as a list:
- digitalocean_droplet

### Expected Behavior
I should be able to pass a list of SSH key fingerprints to be added to a droplet.

### Actual Behavior
To be able to pass more than one SSH key to be added to a droplet I have to make it a string and make sure that `\n` is at the end of each fingerprint. Even than when you do `terraform apply` DiditalOcean will not accept it and send back a 422 error.

### Steps to Reproduce
1. Make a droplet what has more than one ssh key passed to it.

**Comment by andrewsomething** [comment]
Hi @dpisano,

Can you share an example configuration demonstrating this issue? I am successfully able to create a Droplet with multiple SSH keys using fingerprints like so:

```
resource "digitalocean_droplet" "web" {
  image  = "ubuntu-18-04-x64"
  name   = "web-1"
  region = "nyc2"
  size   = "s-1vcpu-1gb"
  ssh_keys = ["b6:2e:fa:ea:96:42:14:1b:62:e2:76:4b:6f:60:1a:e6", "60:e4:a4:d7:ff:52:e3:ea:4b:c4:6f:b6:37:93:0d:a8"]
}
```

**Comment by dpisano** [comment]
I think I found the problem. This is what I was doing. I have been using I think version 0.1.2 and a older version of of terraform for some time. I was tying this on a new system, so I'm using the a newer version now. It looks like what I was tying to do was pass a list var into a list.

```
variable "ssh_fingerprint" {
  description = "SSH Public key hash"
  type        = "list"
  default = ["b6:2e:fa:ea:96:42:14:1b:62:e2:76:4b:6f:60:1a:e6", "60:e4:a4:d7:ff:52:e3:ea:4b:c4:6f:b6:37:93:0d:a8"]
}

resource "digitalocean_droplet" "web" {
  image  = "ubuntu-18-04-x64"
  name   = "web-1"
  region = "nyc2"
  size   = "s-1vcpu-1gb"
  ssh_keys = ["${var.ssh_fingerprint}"]
}
```

**Comment by andrewsomething** [comment]
There have been quite a few changes in the newest version of Terraform (0.12.x), including how list variables are referenced.  

With Terraform v0.12.3 and provider.digitalocean v1.4.0, this should work as expected:

```
variable "ssh_fingerprint" {
  description = "SSH Public key hash"
  type        = "list"
  default = ["b6:2e:fa:ea:96:42:14:1b:62:e2:76:4b:6f:60:1a:e6", "60:e4:a4:d7:ff:52:e3:ea:4b:c4:6f:b6:37:93:0d:a8"]
}

resource "digitalocean_droplet" "web" {
  image  = "ubuntu-18-04-x64"
  name   = "web-1"
  region = "nyc2"
  size   = "s-1vcpu-1gb"
  ssh_keys = var.ssh_fingerprint
}
```

Check out the details here: https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables

Feel free to reopen this if you're still running into issues.
