### ISSUE TITLE
Extend data source types to include lists

### ISSUE THREAD

**Issue by syntaqx** [terraform-providers/terraform-provider-digitalocean#263]
## Feature request: Data source lists, filtering

With a few exceptions, there seems to be quite a few data sources missing from the provider, specifically list methods. I think it would be a massive improvement to be able to work with existing resources, especially in multi-team environments where sources are controlled by other state files.

This is what I've been using to hack the functionality for the time being, it might be useful for the proposal or anyone else who might need it until progress can be made getting this into the provider -- I simply include this in my `.envrc` (you could also use `.bash_profile`):

```sh
#!/usr/bin/env bash
set -e -o pipefail

JQ_FLAGS=${JQ_FLAGS:-"-cer"}

echoerr() { echo "$@" 1>&2; }

reqs=(jq doctl)
for i in "${reqs[@]}"; do
  if ! command -v "$i" &>/dev/null; then
    echoerr "$i is required but is not installed."
    echoerr "Exiting."
    exit 1
  fi
done

doctlwrap() { doctl "$@" -o json; }

describe_account() {
  doctlwrap account get | jq $JQ_FLAGS \
  '{
    uuid,
    email,
    email_verified,
    limits: {
      droplet: .droplet_limit,
      volume: .volume_limit,
      floating_ip: .floating_ip_limit
    },
    status,
    status_message
  }'
}

list_regions() {
  doctlwrap compute region list | jq $JQ_FLAGS \
  '[ .[] | {
    name,
    slug,
    features,
    available
  } ]'
}

list_sizes() {
  doctlwrap compute size list | jq $JQ_FLAGS \
  '[ .[] | {
    slug,
    resources: {
      cpus: .vcpus,
      disk: "\(.disk)GB",
      memory: "\(.memory)MB"
    },
    price: {
      monthly: .price_monthly,
      hourly: .price_hourly
    },
    bandwidth: {
      transfer: "\(.transfer)TB"
    }
  } ]'
}

list_tags() {
  doctlwrap compute tag list | jq $JQ_FLAGS \
  '[ .[] | {
    name,
    resources
  } ]'
}

export TF_VAR_do_account="$(describe_account)"
export TF_VAR_do_regions="$(list_regions)"
export TF_VAR_do_sizes="$(list_sizes)"
export TF_VAR_do_tags="$(list_tags)"
```

Which is then used to populate an equivalent `dynamic_do_variables.tf`:

```hcl
variable "do_account" {
  type = object({
    uuid           = string
    email          = string
    email_verified = bool
    limits         = map(any)
    status         = string
    status_message = string
  })
  default = {
    uuid           = null
    email          = null
    email_verified = null
    limits         = {}
    status         = null
    status_message = null
  }
}

variable "do_regions" {
  type = list(object({
    name      = string
    slug      = string
    features  = list(string)
    available = bool
  }))
  default = [
    { name = null, slug = "nyc1", features : [], available : null },
    { name = null, slug = "nyc2", features : [], available : null },
    { name = null, slug = "nyc3", features : [], available : null },
    { name = null, slug = "ams2", features : [], available : null },
    { name = null, slug = "ams3", features : [], available : null },
    { name = null, slug = "sfo1", features : [], available : null },
    { name = null, slug = "sfo2", features : [], available : null },
    { name = null, slug = "sgp1", features : [], available : null },
    { name = null, slug = "lon1", features : [], available : null },
    { name = null, slug = "fra1", features : [], available : null },
    { name = null, slug = "tor1", features : [], available : null },
    { name = null, slug = "blr1", features : [], available : null },
  ]
}

variable "do_sizes" {
  type = list(object({
    slug = string
    resources = object({
      cpus   = string
      disk   = string
      memory = string
    })
    price = object({
      monthly = number
      hourly  = number
    })
    bandwidth = object({
      transfer = string
    })
  }))
  default = []
}

variable "do_tags" {
  type = list(object({
    name      = any
    resources = any
  }))
  default = []
}
```

# # Proposals

#### `data.digitalocean_account` - Fetch authenticated account

Not really much to say here, just a much needed attribute for audit capabilities

```hcl
data "digitalocean_account" "current" {
    token = var.do_token # optional, defaults to the provider
}
```

#### `data.digitalocean_regions` - List and filter available regions

Obtain a list of regions, their feature sets, current status (a tie into the status API for `degraded` would be game changing) and reference attributes.

```hcl
data "digitalocean_regions" "example" {
}
```

#### `data.digitalocean_images` - List and filter available images

A significant improvement and replacement for the current single-value `image` data source. I would much rather have sort & search features over a collection of image/snapshots and slice the correct target off the set rather than the current functionality of an error bubbling when duplicates are found.

> __Note:__ This can be interchangeably named `snapshots` as well give that the DO marketplace images are just `public` snapshots - there's really not much of a distinction as far as I can tell.

```hcl
data "digitalocean_images" "example" {
    region = "nyc3" # optional
    public = true # optional, defaults to true
}
```

#### `data.digitalocean_sizes` - List and filter available sizes

Given that not all sizes are available for a given region this provides the a significant compatibility improvement. Also allows for dynamic size comparisons with other clouds when trying to normalize slugs across clouds:

```hcl
data "digitalocean_sizes" "example" {
    region = "nyc3" # optional
}
```

#### `data.digitalocean_tags` - List and filter available tags

Extremely useful for investigation of dynamic tagging allocations for resource types or lab environments - Also, I didn't even realize that some of my previous Terraform crashes had left artifact Tags around - They also didn't show up in the UI because there weren't any resources attached to them -- This would've made that more obvious.

```hcl
data "digitalocean_tags" "example" {
}
```

### Resource data filtering & sorting

This is my basic concept for how you can normalize discovery of data & resources across the provider rather than having to implement arbitrary attribute

> __TL;DR:__ Simply add equality checks or regex filter dynamics on any argument or attribute of the resource/datasource. Then, pick a sort & order so the data can come back how you need.

#### Initial usage

```hcl
data "digitalocean_images" "example" {
    # for simple type constraints, compare equality
    filter {
        attribute = "public"
        values = [false]
    }

    # for complex type collections, assert the value is contained within the set
    filter {
        attribute = "regions"
        values = ["sfo2"]
    }
}
```

```hcl
# simple use of regex instead of just string eq, gives plenty of flexibility for edge cases
data "digitalocean_regions" "example" {
    filter {
        field = "slug"
        regex = "^nyc\d{1}$"
    }

    # in-memory sort on the results given the API doesn't consistently expose sorting
    sort = {
        attribute = "created_at"
        direction = "desc"
    }
}
```

There's obviously tons of things that could be added into this in the future, just naming some off the top of my head:

* improve base equality checks with optional search string query syntax & parsing (such as lucene or whatever)
* `GROUP BY` and other sub-select mechanics - Although you can get pretty far with HCL dynamics
* Custom or embedded HCL functional usage within comparisons  (ie leveraging `cidrsubnet()` over non-resolved attributes, etc..)

But I don't think any of those are necessary for an MVP.

Also, I'd add that this system would be a fairly drastic improvement on a existing resource selectors as well, making things far more flexible for improvement.

## Terraform version

```
Terraform v0.12.3
+ provider.digitalocean v1.4.0
```

## References

* __AWS Provider__
  * https://www.terraform.io/docs/providers/aws/d/instances.html#filter
  * https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html
* __Google Cloud Provider__ (Logs)
  * https://www.terraform.io/docs/providers/google/r/logging_project_sink.html#filter
  * https://cloud.google.com/logging/docs/view/advanced-filters

**Comment by Permagate** [comment]
I took a stab on implementing data source for `account` and `sizes`:

### `digitalocean_account`

PR: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/324

Currently I limited the implementation on simply retrieving the account associated with the token used by terraform. `token` parameter might be useful multiple accounts are used, but a naive implementation will store the token value in terraform state file. Any idea on how to approach this securely?

### `digitalocean_sizes`

PR: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/325

Fairly straightforward mapping with the digitalocean V2 sizes API... other than the filter and sort logic that is. In `digitalocean_sizes` PR, I implemented a rudimentary client-side sort and filter logic, with common sort and filter schema/expander helper functions coded separately inside `sort.go` and `filter.go`. The logic is still implemented inside the data source code.

Here is a relatively non-basic example to fetch sizes with virtual CPU 1 or 2 that are available in sgp1 region, then use the cheapest one available:

```hcl
data "digitalocean_sizes" "main" {
  filter {
    key    = "vcpus"
    values = [1, 2]
  }

  filter {
    key    = "regions"
    values = ["sgp1"]
  }

  sort {
    key       = "price_monthly"
    direction = "asc"
  }
}

resource "digitalocean_droplet" "web" {
  image  = "ubuntu-18-04-x64"
  name   = "web-1"
  region = "sgp1"
  size   = element(data.digitalocean_sizes.main.sizes, 0).slug
}
```

### Filter type proposal

Currently the filter is only exact match, but the implementation can be easily extended to include other type of matches. I'm thinking of adding optional `type` attribute in filter schema, like so:

```hcl
data "digitalocean_sizes" "main" {
  filter {
    key     = "slug"
    values  = ["^m-.+"]
    type    = "regex"  // Is either "exact", "regex", "greaterThan", or "lesserThan". Default to "exact".
  }
}

Thought?
```

**Comment by ianwalter** [comment]
I would really like to manage snapshots through Terraform, and without being able to list/filter them, that's not possible.

**Comment by andrewsomething** [comment]
Much of what is described in this issue has been implemented and the linked PRs have been merged. For example, `data.digitalocean_images` supports filtering and sorting: 

https://www.terraform.io/docs/providers/do/d/images.html

**Comment by andrewsomething** [comment]
I'm going to go ahead and close this issue out as we've add much of what this issue requests. If there are uses cases the new data sources do not support or other data sources you'd like to see, please feel free to open specific issues for them.

Thank you to everyone for all the feedback!

**Comment by andrewsomething** [comment]
https://github.com/terraform-providers/terraform-provider-digitalocean/pull/451 will add `data.digitalocean_tags`
