### ISSUE TITLE
digitalocean_record IPv6 address wants to change

### ISSUE THREAD

**Issue by z3ntu** [terraform-providers/terraform-provider-digitalocean#269]
### Terraform Version
```
Terraform v0.12.4
+ provider.digitalocean v1.5.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_record

### Terraform Configuration Files
```hcl
resource "digitalocean_record" "z3ntu-AAAA" {
  domain = digitalocean_domain.z3ntu.name
  type   = "AAAA"
  name   = "@"
  value  = digitalocean_droplet.vps.ipv6_address
}
```

Hi,
Terraform wants to change my DNS entries from the IPv6 "long form" to the "short form"
```
  # digitalocean_record.z3ntu-AAAA will be updated in-place
  ~ resource "digitalocean_record" "z3ntu-AAAA" {
        domain   = "z3ntu.xyz"
        flags    = 0
        fqdn     = "@.z3ntu.xyz"
        id       = "40728886"
        name     = "@"
        port     = 0
        priority = 0
        ttl      = 1800
        type     = "AAAA"
      ~ value    = "2a03:b0c0:0002:00d0:0000:0000:0192:b001" -> "2a03:b0c0:2:d0::192:b001"
        weight   = 0
    }
```
I've been using Terraform for a while and it worked fine before. Maybe something on the DigitalOcean side changed, so they output the non-abbreviated IPv6 addresses for a DNS entry?

This happens with all my AAAA DNS entries configured in Terraform.

If you need any more info, just tell me.

**Comment by andrewsomething** [comment]
This looks to be a change on the DigitalOcean API side, not Terraform. The IPv6 address being returned for Droplets is now using the "short" format for IPv6 address. For example:

```
$ curl -X GET -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DO_TOKEN" \
    "https://api.digitalocean.com/v2/droplets/151344506" \
    | jq .droplet.networks.v6[0].ip_address 

"2604:a880:800:c1::1f3:f001"
```

**Comment by andrewsomething** [comment]
This was confirmed to be a change in the way IPv6 address are returned for Droplets in the DO API. The new format should be stable now. Apologies for the inconvenience.
