### ISSUE TITLE
Update the documentation to v0.12 syntax

### ISSUE THREAD

**Issue by MarianoRD** [terraform-providers/terraform-provider-digitalocean#274]
I know this issue might not be that important, but it's specially useful for the folks that are starting to use the provider and Terraform, to have working examples. Right now, some of the documentation still uses the `v0.11` syntax of Terraform, instead of the new `v0.12` one.

### Terraform Version
`v0.12.0'

#### Data sources
- digitalocean_domain
- digitalocean_floating_ip
- digitalocean_image
- digitalocean_kubernetes_cluster
- digitalocean_record
- digitalocean_volume
- digitalocean_volume_snapshot

#### Resources
- digitalocean_cdn
- digitalocean_certificate
- digitalocean_domain
- digitalocean_droplet_snapshot
- digitalocean_firewall
- digitalocean_floating_ip
- digitalocean_floating_ip_assignment 
- digitalocean_loadbalancer
- digitalocean_kubernetes_cluster
- digitalocean_kubernetes_node_pool
- digitalocean_project
- digitalocean_record 
- digitalocean_spaces_bucket
- digitalocean_ssh_key
- digitalocean_tag
- digitalocean_volume
- digitalocean_volume_attachment
- digitalocean_volume_snapshot

### Expected Behavior
Find out of the box functional examples in the documentation.

### Actual Behavior
The examples need to be changed from 'v0.11' to ' v0.12' syntax.

### Steps to Reproduce
1. Copy and paste the examples of any of the resources listed above.

**Comment by andrewsomething** [comment]
Thanks for raising this. We definitely need to go through and update these to use the current syntax. Before the 0.12 release, I tried to update any syntax that would not be forward compatible with the release. If you've identified any examples that will not run under 0.12, please flag them here so we can prioritize getting them updated ASAP.

**Comment by MarianoRD** [comment]
All the resources listed have examples that do not run. They use the old variable instantiation syntax. So the changes should be easier to spot, I'll take a better look to see if there's anything else.

**Comment by botzill** [comment]
Hi.

Any updates about this?
