### ISSUE TITLE
DO-specific community - Terraform specific or otherwise?

### ISSUE THREAD

**Issue by syntaqx** [terraform-providers/terraform-provider-digitalocean#275]
I'd like to help move some issues that are important to myself and my company along by contributing to this project (and others) - Is there a slack or equivalent that I can join to theorycraft and communicate with others in a more dynamic way than GitHub?

Sorry if this is super obvious but I wasn't able to find anything relevant.

Hope to help out on the project soon, thanks!

**Comment by andrewsomething** [comment]
The [DigitalOcean community site](https://www.digitalocean.com/community/) has a Q&A section that is a great place to get support, but it doesn't currently have features for more open ended discussion. Neither Terraform nor DigitalOcean have public community Slacks. While I do see that having a place for more dynamic conversation could be useful, keeping the GitHub as the canonical place for planning does ensure that decisions are publicly documented. Curious if other contributors have more thoughts on this?

Looking forward to your contributions! Please feel free to reach out if there's anything you need help with.
