### ISSUE TITLE
Project consistently not found on apply

### ISSUE THREAD

**Issue by syntaqx** [terraform-providers/terraform-provider-digitalocean#276]
This may not be a provider-specific bug, but there are currently no outages posted on status.digitalocean.com so I thought I'd report it here just incase it was a bug.

I have a `digitalocean_project` that's fairly vanilla, and seems to work occasionally. However, >50% of `terraform apply`s result in something similar to:

```
→  [master]  infra $ terraform apply -auto-approve
Acquiring state lock. This may take a few moments...
digitalocean_project.default: Refreshing state... [id=<omitted>]

Error: Error reading Project: Error loading resources GET https://api.digitalocean.com/v2/projects/<omitted>/resources: 404 
```

Alternatively, it will also succeed at this point, then fail during assignment like:

```
Error: Error Updating project: Error assigning resources: POST https://api.digitalocean.com/v2/projects/<omitted>/resources: 404 

  on main.tf line 18, in resource "digitalocean_project" "default":
  18: resource "digitalocean_project" "default" {
```

Which is equally frustrating.

### Terraform Version

```
→  [master]  infra $ terraform -v
Terraform v0.12.5
+ provider.digitalocean v1.5.0
```

### Affected Resource(s)

- `digitalocean_project`

### Terraform Configuration Files

I'm able to successfully reproduce this with just:

```hcl
resource "digitalocean_project" "default" {
  name        = "example"
  environment = "development"
  purpose     = "Operational / Developer tooling"
  resources   = []
}
```

### Expected Behavior

The project data should be populated as it exists

### Actual Behavior

More often than not, the project 404's

### Steps to Reproduce

1. Create a new TF repo with a DO project being created
2. `terraform apply`
3. `terraform plan` after the initial creation and watch it fail more often than it succeeds

## Final notes

This could just be the API wigging out and I'm monitoring status.digitalocean.com if anything gets noted, sorry if this isn't accurate because of that.

**Comment by andrewsomething** [comment]
Hi @syntaqx Thanks for opening this issue. I raised it internally at DO with the team responsible for the projects API, and it they were able to track down the problem. It should be resolved now. Please feel free to reopen the issue if you're still seeing problems.
