### ISSUE TITLE
"volume_ids" with counted volumes

### ISSUE THREAD

**Issue by mluscon** [terraform-providers/terraform-provider-digitalocean#28]
Hi,

I stumbled upon an issue with specifying volume ids for volumes created with count. I tried various ways e.g.:
```
volume_ids = ["${"${format("digitalocean_volume.docker_master.%d.id", count.index)}"}"]
```
Which doesn't work because of a nested interpolation or:
```
volume_ids = ["${digitalocean_volume.docker_master.*.id}"]
```
Which neither works since digitalocean doesn't support attaching one volume to more than one droplet.
Is there any way how I can achieve this?

**Comment by tombuildsstuff** [comment]
Hey @mluscon 

Given you're creating multiple volumes with `count` - you should be able to access the values using [the `element` interpolation function](https://www.terraform.io/docs/configuration/interpolation.html#element-list-index-)

This can be used in code as shown:

```
volume_ids = [ "${element(digitalocean_volume.docker_master.*.id, count.index)}" ]
```

For example, the following example should work: :)

```
resource "digitalocean_volume" "docker_master" {
  region      = "nyc1"
  name        = "vol${count.index}"
  size        = 100
  count       = 3
  description = "an example volume"
}

resource "digitalocean_droplet" "docker_master" {
  name       = "docker${count.index}"
  size       = "1gb"
  count      = 3
  image      = "coreos-stable"
  region     = "nyc1"
  volume_ids = [ "${element(digitalocean_volume.docker_master.*.id, count.index)}" ]
}
```

Would it be possible for you to take a look and see if that solves your issue?

Thanks!

**Comment by mluscon** [comment]
It works like a charm. Thank you!
