### ISSUE TITLE
DigitalOcean Droplet not destroyed despite Terraform reporting destruction a success.

### ISSUE THREAD

**Issue by manibatra** [terraform-providers/terraform-provider-digitalocean#283]
We ran the terraform job to delete the droplet which was reported as a success. But the droplet was not destroyed and was running when we logged into the dashboard. In the past, we have not noticed that such a droplet rejoins our cluster if not manually deleted from the dashboard.

### Terraform Version
`terraform version = 0.11.1`
`terraform-provider-digitalocean version = 1.0.2`

### Affected Resource(s)
- digitalocean_droplet

### Debug Output
Terraform returning successful destruction : 
```
module.delivery-12.module.delivery.digitalocean_droplet.droplet: Destroying... (ID: 132167273)
module.delivery-12.delivery.digitalocean_droplet.droplet: Still destroying... (ID: 132167273, 10s elapsed)
module.delivery-12.module.delivery.digitalocean_droplet.droplet: Destruction complete after 11s
```

### Expected Behavior
The droplet is destroyed.

### Actual Behavior
The droplet was not destroyed and was running when logged into the DigitalOcean dashboard. Had to be destroyed from the dashboard.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. We have seen this issue happen for droplets that are having issues and are undergoing/will undergo migration due to physical host issues. Hence, find a similar droplet.
2. `terraform apply apply.tfplan` where the plan has droplet marked for destruction.
3. The droplet is running when logged into the DigitalOcean dashboard despite Terraform indicating successful destruction.

**Comment by eddiezane** [comment]
@manibatra thanks for reporting this and apologies for any headaches this caused y'all.

Digging into this with the team. My first reaction is this is something we might need to address internally as opposed to in the provider.
