### ISSUE TITLE
Changing count causes recreation volume attachment

### ISSUE THREAD

**Issue by okgolove** [terraform-providers/terraform-provider-digitalocean#292]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.14
+ provider.digitalocean v1.6.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_volume_attachment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "digitalocean_droplet" "kafka" {
  count              = "${var.kafka_count}"
  image              = "${data.digitalocean_droplet_snapshot.kafka_snapshot.id}"
  name               = "kafka-${format("%03d", count.index + 1)}"
  region             = "${var.do_region}"
  size               = "${var.kafka_size}"
  user_data          = "${element(data.template_file.kafka_userdata.*.rendered, count.index)}"
  private_networking = true
  ssh_keys           = ["${digitalocean_ssh_key.ssh_key.fingerprint}"]
}


resource "digitalocean_volume" "kafka" {
  count                   = "${var.kafka_count}"
  region                  = "${var.do_region}"
  name                    = "kafka-${format("%03d", count.index + 1)}"
  size                    = "100"
  initial_filesystem_type = "ext4"
}

resource "digitalocean_volume_attachment" "kafka" {
  count      = "${var.kafka_count}"
  droplet_id = "${element(digitalocean_droplet.kafka.*.id, count.index)}"
  volume_id  = "${element(digitalocean_volume.kafka.*.id, count.index)}"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
What should have happened?
Volumes aren't reattached, new droplets and volumes are created and attached.

### Actual Behavior
What actually happened?
```
-/+ digitalocean_volume_attachment.kafka[0] (new resource required)
      id:                           "158088385-76e78d30-d25c-11e9-b0e6-0a58ac1480a3-20190908183122109800000001" => <computed> (forces new resource)
      droplet_id:                   "158088385" => "0" (forces new resource)
      volume_id:                    "76e78d30-d25c-11e9-b0e6-0a58ac1480a3" => "${element(digitalocean_volume.kafka.*.id, count.index)}" (forces new resource
)

-/+ digitalocean_volume_attachment.kafka[1] (new resource required)
      id:                           "158088386-76f44ccd-d25c-11e9-b0e6-0a58ac1480a3-20190908183122145100000002" => <computed> (forces new resource)
      droplet_id:                   "158088386" => "0" (forces new resource)
      volume_id:                    "76f44ccd-d25c-11e9-b0e6-0a58ac1480a3" => "${element(digitalocean_volume.kafka.*.id, count.index)}" (forces new resource
)

-/+ digitalocean_volume_attachment.kafka[2] (new resource required)
      id:                           "158088387-76e3ac2f-d25c-11e9-ba3e-0a58ac1480f1-20190908183122692600000003" => <computed> (forces new resource)
      droplet_id:                   "158088387" => "0" (forces new resource)
      volume_id:                    "76e3ac2f-d25c-11e9-ba3e-0a58ac1480f1" => "${element(digitalocean_volume.kafka.*.id, count.index)}" (forces new resource
)

  + digitalocean_volume_attachment.kafka[3]
      id:                           <computed>
      droplet_id:                   "0"
      volume_id:                    "${element(digitalocean_volume.kafka.*.id, count.index)}"

  + digitalocean_volume_attachment.kafka[4]
      id:                           <computed>
      droplet_id:                   "0"
      volume_id:                    "${element(digitalocean_volume.kafka.*.id, count.index)}"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. set `kafka_count = 3`
2. `terraform apply`
3. set `kafka_count = 5`
4. `terraform apply`

**Comment by andrewsomething** [comment]
I'm not able to reproduce this issue. Looking at the plan output above, it doesn't show new volumes being created. It does show the `digitalocean_volume_attachment` "resources" being re-created. These are "virtual" resources representing the link between the existing Droplets and volumes. Recreating a `digitalocean_volume_attachment` doesn't actually recreate a volume. I've tried both with  v0.11.14 and v0.12.8. In both cases, the volumes created in the first run remain attached to the same Droplets after increasing the count and re-applying.

When using a newer version of Terraform the output is different and hides some of the noise. Using v0.12.8 when I increase `kafka_count = 2` to `kafka_count = 3`, running plan reports:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # digitalocean_droplet.kafka[2] will be created
  + resource "digitalocean_droplet" "kafka" {
      + backups              = false
      + created_at           = (known after apply)
      + disk                 = (known after apply)
      + id                   = (known after apply)
      + image                = "ubuntu-18-04-x64"
      + ipv4_address         = (known after apply)
      + ipv4_address_private = (known after apply)
      + ipv6                 = false
      + ipv6_address         = (known after apply)
      + ipv6_address_private = (known after apply)
      + locked               = (known after apply)
      + memory               = (known after apply)
      + monitoring           = false
      + name                 = "kafka-003"
      + price_hourly         = (known after apply)
      + price_monthly        = (known after apply)
      + private_networking   = true
      + region               = "nyc3"
      + resize_disk          = true
      + size                 = "s-1vcpu-1gb"
      + status               = (known after apply)
      + urn                  = (known after apply)
      + vcpus                = (known after apply)
      + volume_ids           = (known after apply)
    }

  # digitalocean_volume.kafka[2] will be created
  + resource "digitalocean_volume" "kafka" {
      + droplet_ids             = (known after apply)
      + filesystem_label        = (known after apply)
      + filesystem_type         = (known after apply)
      + id                      = (known after apply)
      + initial_filesystem_type = "ext4"
      + name                    = "kafka-003"
      + region                  = "nyc3"
      + size                    = 10
      + urn                     = (known after apply)
    }

  # digitalocean_volume_attachment.kafka[2] will be created
  + resource "digitalocean_volume_attachment" "kafka" {
      + droplet_id = (known after apply)
      + id         = (known after apply)
      + volume_id  = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

Let us know if this answers your concern or if there's more information you can provide to help us better understand the problem.

**Comment by okgolove** [comment]
> Recreating a digitalocean_volume_attachment doesn't actually recreate a volume. I've tried both with v0.11.14 and v0.12.8. In both cases, the volumes created in the first run remain attached to the same Droplets after increasing the count and re-applying.

It doesn't but it unmounts the volume. This is the problem.

**Comment by alor** [comment]
I'm having the same issue. if I increase the droplet count all the previous droplets have the volume unmounted and doing this in production is really a pain...

**Comment by alor** [comment]
oh... it seems that with:
```
Terraform v0.12.9
+ provider.digitalocean v1.8.0
```
the old droplets volume attachments do not get unmounted if the counter is changed.
can you confirm the issue was resolved in the latest versions?

thank you

**Comment by okgolove** [comment]
Unfortunately, I'm not able to migrate to 0.12.

Btw, there is a workaround, you can temporarily add ignore_changes section when you want to change the count:

```
lifecycle {
  ignore_changes = ["droplet_id"]
}
```

**Comment by andrewsomething** [comment]
Thanks for providing your work around. As this issue does not exist with Terraform >= 0.12 and a workaround exists for earlier versions, I'm going to close this out for now.
