### ISSUE TITLE
Mark database_cluster resource's password and uri attributes as sensitive

### ISSUE THREAD

**Issue by andrewsomething** [terraform-providers/terraform-provider-digitalocean#298]
The [password](https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_database_cluster.go#L111) and [uri](https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_database_cluster.go#L96) attributes of the `digitalocean_database_cluster` resource and datasource contain the password for the default database user. These should be marked as sensitive to prevent them from being logged in plain text.

For reference, the Terraform provider SDK allows schema attributes to be [marked as sensitive](https://github.com/hashicorp/terraform-plugin-sdk/blob/9f0df37a8fdb2627ae32db6ceaf7f036d89b6768/helper/schema/schema.go#L245-L249):

 	// Sensitive ensures that the attribute's value does not get displayed in
	// logs or regular output. It should be used for passwords or other
	// secret fields. Future versions of Terraform may encrypt these
	// values. 

For example, this PR implements something similar for the `kubernete_cluster` resource: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/289

**Comment by clickyotomy** [comment]
@andrewsomething - Can I take this up as well? In addition to `password` and `uri`, I guess we can also mark `private_uri` (introduced by https://github.com/terraform-providers/terraform-provider-digitalocean/pull/300) as sensitive?

**Comment by andrewsomething** [comment]
@clickyotomy It's all yours! :grinning:
