### ISSUE TITLE
Provide private connection details for database_cluster resource

### ISSUE THREAD

**Issue by andrewsomething** [terraform-providers/terraform-provider-digitalocean#299]
Since the `digitalocean_database_cluster` resource and datasource were first implemented, DigitalOcean has added support for database connections over the private network. The connection information for the private network should be exposed via computed attributes: `private_host` and `private_uri`

API docs: https://developers.digitalocean.com/documentation/v2/#create-a-new-database-cluster
godo: https://godoc.org/github.com/digitalocean/godo#Database

**Comment by clickyotomy** [comment]
Hello! Can I work on this?

**Comment by andrewsomething** [comment]
@clickyotomy Go for it! Let me know if you have any questions.
