### ISSUE TITLE
digitalocean_kubernetes_cluster - Enable auto upgrade

### ISSUE THREAD

**Issue by pjanuario** [terraform-providers/terraform-provider-digitalocean#317]
Auto upgrade feature is now available on the DO API along with the maintenance policy, would be good to be able to specify this property in terraform.

https://developers.digitalocean.com/documentation/v2/#create-a-new-kubernetes-cluster

**Comment by lfarnell** [comment]
I think this is a duplicate of #237

**Comment by pjanuario** [comment]
My fault, didnt see it in the backlog.
