### ISSUE TITLE
Remaining Spaces resources and data sources needed

### ISSUE THREAD

**Issue by lfarnell** [terraform-providers/terraform-provider-digitalocean#330]
Just trying to highlight the remaining resources and data sources missing to complete Spaces support in Terraform.

- Spaces Bucket Object Resource

- Spaces Bucket Lifecycle Resource

- Spaces Bucket Object Datasource

- Spaces Bucket Objects Datasource

These new resources would bring the DO provider in line with the AWS S3 resources in terms of supported feature set.

**Comment by tdyas** [comment]
https://github.com/terraform-providers/terraform-provider-digitalocean/pull/408 implements `digitalocean_spaces_bucket_object`.

**Comment by tdyas** [comment]
https://github.com/terraform-providers/terraform-provider-digitalocean/pull/409 implements `versioning` argument on `digitalocean_spaces_bucket`.

**Comment by andrewsomething** [comment]
Think we should now have all of this covered thanks to @tdyas!
