### ISSUE TITLE
Updating Kubernetes cluster version should not cause replacement

### ISSUE THREAD

**Issue by ddollar** [terraform-providers/terraform-provider-digitalocean#332]
Hi there,

Changing the version of a Kubernetes cluster should not recreate the resource.

An upgrade API is available: https://developers.digitalocean.com/documentation/v2/#upgrade-a-kubernetes-cluster

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_kubernetes_cluster

### Expected Behavior
Kubernetes cluster upgrades without being replaced.

### Actual Behavior
The Kubernetes cluster is replaced.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Change the `version` attribute of a `digitalocean_kubernetes_cluster`
2. `terraform apply`

**Comment by botzill** [comment]
Yes, this is really annoying to upgrade a k8s cluster, you need to recreate it. Is there any other, easy way, to achieve this?

**Comment by gugu** [comment]
Even more - DO can upgrade cluster on their own automatically. And terraform tries to destroy the cluster because of version mismatch

**Comment by botzill** [comment]
well, I guess that if we upgrade the cluster using the DO UI and then we change that version in the terraform state file(if not encrypted) then it may work, thought did not test this yet.
