### ISSUE TITLE
Add Container Registry support

### ISSUE THREAD

**Issue by eddiezane** [terraform-providers/terraform-provider-digitalocean#335]
Initial support landed in [godo](https://github.com/digitalocean/godo/blob/master/registry.go).

This might be a good first issue for @Zelgius. We can work together on this one if you'd like.

**Comment by zachgersh** [comment]
@eddiezane - do we want to wait for this to come out of beta before we move it into terraform? Or do we just do the work beforehand to be prepared for when it ships? I know @andrewsomething will want some messaging about how this functionality is in beta when we ship it.

**Comment by eddiezane** [comment]
Think the best way forward is to silently add support until it's in open beta for folks to use.
