### ISSUE TITLE
DC/OS taking hours to create the master

### ISSUE THREAD

**Issue by ntk860** [terraform-providers/terraform-provider-digitalocean#34]
I am trying to create my DC/OS cluster on digitalocean, when I do terraform apply, it creates the master (I can see the machine on digitalocean) but it is taking hours on this step

digitalocean_droplet.dcos_master: Still creating... (1h11m30s elapsed)

can someone help me please

**Comment by radeksimko** [comment]
Hi @ntk860 ,
to better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://www.terraform.io/docs/internals/debugging.html) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by andrewsomething** [comment]
As this has been waiting a response for some time now, I'm going to go ahead and close the issue. If you experience the problem again or if you have additional information to provide, please don't hesitate to reopen it.
