### ISSUE TITLE
New resource: digitalocean_database_firewall

### ISSUE THREAD

**Issue by andrewsomething** [terraform-providers/terraform-provider-digitalocean#340]
The DigitalOcean API now supports managing a database cluster’s firewall rules (known as “trusted sources” in the control panel):

https://developers.digitalocean.com/documentation/changelog/api-v2/managed-databases-firewall-and-sql-mode-management/

This should be supported in Terraform as well. A potential config may look like:

```hcl
resource "digitalocean_database_firewall" "example" {
  cluster_id = digitalocean_database_cluster.postgres-example.id

  rule {
    type  = "droplet"
    value = digitalocean_droplet.web.id
  }

  rule {
    type  = "ip_addr"
    value = data.aws_instance.public_ip
  }
}
```

**Comment by eddiezane** [comment]
Closed via #348
