### ISSUE TITLE
why digitalocean_record does require value to end in dot

### ISSUE THREAD

**Issue by botzill** [terraform-providers/terraform-provider-digitalocean#352]
### Terraform Version
Terraform v0.12.18

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_record

### Terraform Configuration Files
```hcl
resource "digitalocean_record" "do-mg-domain-sending" {
  count = length(mailgun_domain.mg-domain.sending_records)

  domain = var.main_domain
  type   = mailgun_domain.mg-domain.sending_records[count.index].record_type
  name   = replace(mailgun_domain.mg-domain.sending_records[count.index].name, ".${var.main_domain}", "")
  value  = "${mailgun_domain.mg-domain.sending_records[count.index].value}"
  ttl = 300
}
```

### Panic Output
```
Error: Failed to update record: PUT https://api.digitalocean.com/v2/domains/crawless.com/records/85729436: 422 Data needs to end with a dot (.)

  on module.tf line 34, in resource "digitalocean_record" "do-mg-domain-sending":
  34: resource "digitalocean_record" "do-mg-domain-sending" {

```
### Expected Behavior
Create records like TXT where we don't need to setup the `dot` at the end.

### Actual Behavior
Gives the error above.

**Comment by andrewsomething** [comment]
Hi @botzill, 

Can you confirm that the type really evaluates to `TXT`? I'm unable to reproduce this using a minimal example. This works as expected for me:

```
resource "digitalocean_record" "test" {
  domain = "do-test.ml"
  type   = "TXT"
  name   = "foo.do-test.ml"
  value  = "_key=value"
  ttl    = 300
}
```

If you run apply in debug mode (`TF_LOG=DEBUG terraform apply`) we can see the body actual request that is made to the DO API.

**Comment by vilified** [comment]
> Hi @botzill,
> 
> Can you confirm that the type really evaluates to `TXT`? I'm unable to reproduce this using a minimal example. This works as expected for me:
> 
> ```
> resource "digitalocean_record" "test" {
>   domain = "do-test.ml"
>   type   = "TXT"
>   name   = "foo.do-test.ml"
>   value  = "_key=value"
>   ttl    = 300
> }
> ```
> 
> If you run apply in debug mode (`TF_LOG=DEBUG terraform apply`) we can see the body actual request that is made to the DO API.
