### ISSUE TITLE
Provider doesn't support resizing volumes that are attached to droplets

### ISSUE THREAD

**Issue by mkeen** [terraform-providers/terraform-provider-digitalocean#357]
### Terraform Version
Terraform v0.12.18

### Affected Resource(s)
digitalocean_volume + digitalocean_droplet

### Debug Output
Error: Error resizing volume (87e0dabf-33f7-11ea-8ab5-0a58ac1444a0): POST https://api.digitalocean.com/v2/volumes/87e0dabf-33f7-11ea-8ab5-0a58ac1444a0/actions: 422 (request "52408717-cfb6-470d-9e53-f174f53e6aa9") Block Storage resizing is temporarily disabled for this Droplet. Please reach out to our Support team with any further questions or concerns

  on modules/salt-master/salt-master.tf line 42, in resource "digitalocean_volume" "storage":
  42: resource "digitalocean_volume" "storage" {

### Expected Behavior
Droplet should be powered down, then the volume should be resized

### Actual Behavior
Terraform just gives up. If I manually power down the droplet, I can resize the volume just fine, and when I manually power it back on, everything looks good.

**Comment by eddiezane** [comment]
@mkeen This one is tricky. I don't think Terraform should ever be powering off your servers but I can see the need for some workflow here.

Have you put any thought/hacks into this since opening it?

**Comment by eddiezane** [comment]
Technically the API flow here is to [detach](https://developers.digitalocean.com/documentation/v2/#remove-a-block-storage-volume-from-a-droplet) and then issue the [resize](https://developers.digitalocean.com/documentation/v2/#resize-a-volume)

**Comment by mkeen** [comment]
@eddiezane Hmmm, personally, I’d rather see the droplet powered down than simply detaching the storage. The latter seems like it’d be devastating for running applications that are reading/writing from the mount.  
  
I’m not sure why Terraform shouldn’t power stuff down. I believe that’s how droplet resizing works now.

**Comment by eddiezane** [comment]
@mkeen that's good feedback. Everyone's use case will definitely vary. With Kubernetes for example volumes are attached and detached as pods get rescheduled. Powering off worker nodes to do this would basically be impossible.

**Comment by eddiezane** [comment]
Actually—I've been derping here.

You should be able to resize an attached volume without needing to power off or detach it. I just tested this to confirm with [this config](https://www.terraform.io/docs/providers/do/r/volume_attachment.html#example-usage).

Sounds like you might have hit something different here. If the problem persists let's open a support ticket and debug that.
