### ISSUE TITLE
Support Kubernetes persistent node pool labels

### ISSUE THREAD

**Issue by timoreimann** [terraform-providers/terraform-provider-digitalocean#371]
Recently, DigitalOcean's Kubernetes offering started to support setting Kubernetes labels on node pools that would persist on nodes associated with a particular pool. Labels can be set on any node pool objects by passing in a set of key/value pairs. See also [the announcement in the DigitalOcean API change log](https://developers.digitalocean.com/documentation/changelog/api-v2/kubernetes-node-labels/).

The godo library has been updated in digitalocean/godo#293 (as well as doctl in digitalocean/doctl#731). It would be great to see matching support in the Terraform provider.

/cc @eddiezane

**Comment by tdyas** [comment]
https://github.com/terraform-providers/terraform-provider-digitalocean/pull/379
