### ISSUE TITLE
Snapshot cannot be detached from droplet and gets destroyed with it

### ISSUE THREAD

**Issue by kgizdov** [terraform-providers/terraform-provider-digitalocean#372]
Hi,

So normally, when using the web interface or DigitalOcean's API directly, one can create a snapshot of a droplet, then destroy the droplet and then use the snapshot to recreate that droplet. This is currently impossible with terraform provider for digitalocean.

If I create a droplet, then create the snapshot using terraform, as soon as I remove the droplet I get a `droplet urn undefined`(as the droplet is going to be destroyed) and cannot run terraform until the syntax error is fixed. However, to fix the syntax error one needs to remove the snapshot definition (as the syntax requires a valid droplet urn), which in turn destroys the snapshot.

Basically, the droplet is gone and its snapshot too. Adding a data entry for the snapshot does not help. Good thing there were external backups or a lot of data would have been lost.

### Terraform Version
Terraform v0.12.20
+ provider.digitalocean v1.14.0
+ provider.external v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_droplet
- digitalocean_droplet_snapshot

### Terraform Configuration Files
```hcl
resource "digitalocean_droplet" "name1" {
  name   = "name1"
  size   = var.do_sizes["do_big_size"]  # s-2vcpu-4gb
  image  = var.debian10_slug  # debian-10-x64
  region = var.region  # lon1
  ipv6   = true
  private_networking = true
  ssh_keys = [
    digitalocean_ssh_key.deployssh.fingerprint
  ]
  tags   = [
    "name1",
  ]
  lifecycle {
    ignore_changes = [image]
  }
}

resource "digitalocean_droplet_snapshot" "name1-snapshot" {
  droplet_id = digitalocean_droplet.name1.id
  name       = "name1-snapshot-01"
}

```
### Expected Behavior
Once created a snapshot should exist on its own, detached from a droplet and not needed a droplet urn, so that a droplet could be easily recreated after.

### Actual Behavior
Snapshot once created remain associate with a droplet and are destroyed with the droplet, completely making the data unrecoverable.

### Steps to Reproduce
1. add a droplet
2. create a snapshot
3. `terraform apply`
4. remove droplet
5. get syntax error
6. remove snapshot
7. `terraform apply`
8. lose all data

### Important Factoids
N/A

### References
Could not find any

**Comment by andrewsomething** [comment]
If you want a snapshot generated with Terraform to persist after removing the Droplet resource, reference its ID directly rather than inferring it from the Droplet.

```
resource "digitalocean_droplet_snapshot" "name1-snapshot" {
  droplet_id = 123456
  name       = "name1-snapshot-01"
}
```

> 6. remove snapshot

That will always destroy the snapshot. Terraform is declarative. If you remove something from a configuration, it will be destroyed.

If your use case is automating the creation of long lived snapshots as backups for your Droplet. You might be better off using `doctl` or the API directly. You can then use the data source to access it via Terraform.
