### ISSUE TITLE
Feature request: Retry API calls

### ISSUE THREAD

**Issue by mleonhard** [terraform-providers/terraform-provider-digitalocean#377]
### Terraform Version
```
$ terraform -version
Terraform v0.12.18
+ provider.digitalocean v1.14.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.tls v2.1.1
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `https://api.digitalocean.com/v2/droplets/180058366`

### Expected Behavior
Retry the failing API call repeatedly, giving up after a reasonable time (about 5 mins).

### Actual Behavior
```
module.docker_droplet.digitalocean_droplet.main: Refreshing state... [id=180058366]

Error: Error retrieving droplet: GET https://api.digitalocean.com/v2/droplets/180058366: 504 <!DOCTYPE html>
<html>
<head>
  <title>DigitalOcean - Something went wrong!</title>
  ...
</head>

<body>
  <div class="header">
    <a href="https://www.digitalocean.com"><img src="data:image/png; ..."></a>
  </div>
  <div class="waves"></div>
  <div class="oops-copy">
    <h1>Looks like something went wrong...</h1>
    <p class="sub-copy">If this keeps happening, check out <a href="https://status.digitalocean.com/">status.digitalocean.com</a>.</p>
    <div class="cf-error-details cf-error-504">
  <h1>Gateway time-out</h1>
  <p>The web server reported a gateway time-out error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 563ce3c33dcded77</li>
    <li>Your IP address: 64.124.137.130</li>
    <li>Error reference number: 504</li>
    <li>Cloudflare Location: San Jose</li>
  </ul>
</div>

  </div>
</body>
</html>
```

### Steps to Reproduce
1. Wait until around midnight Pacific time.
1. `terraform apply`

**Comment by andrewsomething** [comment]
This is definitely something that needs to be implemented. There had been a hope that `godo` (the DigitalOcean library we use to interact with the API) would grow some functionality for this, but it is seeming more likely that we'll need to add handle it directly in the Terraform provider.

There is an existing issue tracking this request: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/235 Please follow there for updates. If I've misunderstood the issue, please feel free to reopen.
