### ISSUE TITLE
Add provider.digitalocean.spaces_endpoint and SPACES_ENDPOINT env var

### ISSUE THREAD

**Issue by mleonhard** [terraform-providers/terraform-provider-digitalocean#384]
### Terraform Version
```
Terraform v0.12.20
+ provider.digitalocean v1.14.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_spaces_bucket

### Important Factoids
Currently, the [`digitalocean` Terraform provider](https://www.terraform.io/docs/providers/do/) allows specifying an `api_endpoint` attribute.  This seems to be used mostly for testing the provider.  I wish to configure the provider to talk to a fake S3 service ([LocalStack](https://github.com/localstack/localstack)) for local testing of my service deployments.  Please consider adding a `spaces_endpoint` attribute to the provider to accommodate my use-case. 

The change would be made in `spacesClient()` in [config.go](https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/config.go) .

**Comment by andrewsomething** [comment]
:+1:  This is a like something we should support.

**Comment by andrewsomething** [comment]
Fixed via https://github.com/terraform-providers/terraform-provider-digitalocean/pull/407
