### ISSUE TITLE
Spaces:  Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Macbet** [terraform-providers/terraform-provider-digitalocean#387]
Hi there!

### Terraform Version
 Terraform v0.12.21
 provider.digitalocean v1.14.0

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_spaces_bucket

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "digitalocean" {
  version           = "~>1.14"
  token             = var.do_token
  spaces_access_id  = var.do_access_key
  spaces_secret_key = var.do_secret_key
}

variable "do_token" {}
variable "do_secret_key" {}
variable "do_access_key" {}

resource "digitalocean_spaces_bucket" "test" {
  name   = "example-example"
  acl    = "private"
  region = "ams3"
}
```

### Debug Output
https://gist.github.com/Macbet/0fa9de09a5024833d9774f78a412a4bc - debug gist

### Expected Behavior
DigitalOcean Spaces is created

### Actual Behavior

> digitalocean_spaces_bucket.test: Creating...
> 
> Error: Provider produced inconsistent result after apply
> 
> When applying changes to digitalocean_spaces_bucket.test, provider
> "registry.terraform.io/-/digitalocean" produced an unexpected new value for
> was present, but now absent.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply -auto-approve`

**Comment by andrewsomething** [comment]
Hi @Macbet,

Sorry that you're running into issues. I can reproduce this in the AMS3 region only. This looks to be related to the fact that new bucket creates for Spaces in AMS3 are not currently supported:
 
https://www.digitalocean.com/docs/release-notes/upcoming/spaces-ams3/

The Spaces API seems to respond successfully at first but subsequent requests 404:

```
$ aws --profile do s3 mb --endpoint=https://ams3.digitaloceanspaces.com s3://foo-0000001 --region us-east-1
make_bucket: foo-0000001

$ aws --profile do s3api head-bucket --endpoint=https://ams3.digitaloceanspaces.com --bucket foo-0000001

An error occurred (404) when calling the HeadBucket operation: Not Found
```

I'm flagging this for the Spaces team at DigitalOcean to investigate as this is definitely a poor user experience. Capacity in AMS3 is scheduled to be expanded soon. In the meantime, you should be able to use other regions.

**Comment by Macbet** [comment]
Thank you very much for the answer, then I close these issues
