### ISSUE TITLE
Add provider.digitalocean.spaces_endpoint

### ISSUE THREAD

**Issue by mleonhard** [terraform-providers/terraform-provider-digitalocean#389]
### Terraform Version
```
Terraform v0.12.20
+ provider.digitalocean v1.14.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `provider.digitalocean`
- `digitalocean_spaces_bucket`

### Important Factoids
I wish to use the provider with a fake S3 service ([LocalStack](https://github.com/localstack/localstack)) for local testing.  Please consider adding a `spaces_endpoint` provider argument to allow this.

The change would be made in `spacesClient()` in [`config.go`](https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/config.go) .

This new provider argument would be similar to the existing [`api_endpoint`](https://www.terraform.io/docs/providers/do/) argument.

**Comment by andrewsomething** [comment]
Closing this one out in favor or https://github.com/terraform-providers/terraform-provider-digitalocean/issues/384 as it appears to be a duplicate. Feel free to reopen if I've misunderstood the issue.
