### ISSUE TITLE
Cannot read k8s_cluster data with provider 1.15

### ISSUE THREAD

**Issue by lukoyanov** [terraform-providers/terraform-provider-digitalocean#399]
My terraform scripts with defined data resource (digitalocean_kubernetes_cluster) is no longer works with new provider version.

### Terraform Version
0.12.19

### Affected Resource(s)
Data resources:
- digitalocean_kubernetes_cluster

### Expected Behavior
data object should be retrieved successfully.

### Actual Behavior
Error is logged:
```
 Error: No default node pool was found; the default node pool must have the `terraform:default-node-pool` tag
   on main.tf line 29, in data "digitalocean_kubernetes_cluster" "k8s":
   29: data "digitalocean_kubernetes_cluster" "k8s" {
```

### Steps to Reproduce
1.  Add your k8s cluster as a data resource (digitalocean_kubernetes_cluster)
2. `terraform apply`

**Comment by andrewsomething** [comment]
Thank you so much for flagging this issue. A fix was just release in version 1.15.1. You can upgrade to it with:

    terraform init -upgrade
