### ISSUE TITLE
Error creating VPC: POST https://api.digitalocean.com/v2/vpcs: 404

### ISSUE THREAD

**Issue by Vendin** [terraform-providers/terraform-provider-digitalocean#415]
Hi

### Terraform Version
```
Terraform v0.12.24
+ provider.digitalocean v1.16.0
+ provider.random v2.2.1
```

### Affected Resource(s)
```
digitalocean_kubernetes_cluster.sg
digitalocean_project.n
```

### Terraform Configuration Files
```hcl

resource "digitalocean_vpc" "private_network" {
  name     = "private-network"
  region   = "ams3"
  ip_range = "10.10.10.0/24"
}

```

### Panic Output
```
Error: Error creating VPC: POST https://api.digitalocean.com/v2/vpcs: 404 

  on vpc.tf line 2, in resource "digitalocean_vpc" "private_network":
   2: resource "digitalocean_vpc" "private_network" {

```

### Expected Behavior
Create VPC

### Actual Behavior
Error 404

### Steps to Reproduce
`terraform apply`

**Comment by lfarnell** [comment]
@Vendin I believe the issue is that VPC's haven't been enabled for your account at this time. Can you create a VPC from the web UI?

**Comment by Vendin** [comment]
@lfarnell I can not. How do I enable the VPC for my account?

**Comment by andrewsomething** [comment]
Hey @Vendin. VPC support is being rolled out incrementally. When it is enabled on your account, you should be able to see it at: https://cloud.digitalocean.com/networking/vpc

I'm not able to say when any specific account will receive access, but I would expect it to be much more widely available soon.

Sorry for the confusion!

**Comment by andrewsomething** [comment]
VPCs should now be enabled for all accounts: https://blog.digitalocean.com/vpc-trust-platform/

**Comment by Vendin** [comment]
Thanks
