### ISSUE TITLE
Do not use this digitalocean!

### ISSUE THREAD

**Issue by Vendin** [terraform-providers/terraform-provider-digitalocean#433]
Hi.
I have been waiting for VPC functional for several weeks. https://github.com/terraform-providers/terraform-provider-digitalocean/issues/415
When it was added, I immediately used it in my project.
And Digitalocean blocked my account without explaining the reasons and did not tell me anything.
I lost work on which I worked for several weeks.
I urge everyone to use anything AWS, GCP, Azure, but not this garbage ocean.
Digitalocean doesn't care about its customers!

**Comment by ximon18** [comment]
Sorry to hear you had a bad experience but as a counter point, and I’m not affiliated in any way with DigitalOcean, I continue to be impressed after around a year of using their platform and their customer service. 

Perhaps a GitHub issue is not the right place to raise such a complaint, especially as this repository is specific to Terraform integration and has nothing to do with DigitalOcean customer service actions.

**Comment by andrewsomething** [comment]
Hi @Vendin,

I'm sorry to hear about the problem with your DigitalOcean account. Issues on GitHub are not a good way to resolve account problems. Please reach out directly to the DigitalOcean support team for assistance:

https://www.digitalocean.com/support/
