### ISSUE TITLE
Kubernetes cluster and VPC region matching should be checked

### ISSUE THREAD

**Issue by nrmitchi** [terraform-providers/terraform-provider-digitalocean#434]
First off, this may be more of an issue on the digital ocean side, but the behaviour impacts this provider.

If a kubernetes cluster is created while specifying a `vpc_uuid` there is no validation that the vpc and cluster regions are compatible; at the current time, that means they must match.

### Terraform Version
```
Terraform v0.12.24
+ provider.digitalocean v1.16.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_kubernetes_cluster
- digitalocean_vpc

### Terraform Configuration Files
```hcl


resource "digitalocean_vpc" "example" {
  name   = "example-vpc"

  region   = "nyc3"
  ip_range = "10.0.0.0/16"
}

resource "digitalocean_kubernetes_cluster" "orchestrator" {
  name    = "cluster"
  region  = "nyc1"

  vpc_uuid = digitalocean_vpc.example.id

  # Grab the latest version slug from `doctl kubernetes options versions`
  version = "1.17.5-do.0"
}
```

### Expected Behavior
If the regions don't match, the cluster specification is invalid, and should not attempt to create.

### Actual Behavior
The cluster creation was attempted and hung until timeout every time. After terraform shut down, the cluster continued to attempt to create indefinitely. No indication in Terraform output or the DO web panel indicated that there was any issue.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by andrewsomething** [comment]
Thanks for flagging this issue! I've raised it with the teams involved internally. The underlying problem will be corrected on the DigitalOcean API side. The request should should fail validation and be rejected immediately. That said, I see some room for improvement on the Terraform side as well. PR incoming.
