### ISSUE TITLE
Error deleting VPC

### ISSUE THREAD

**Issue by magsoftware** [terraform-providers/terraform-provider-digitalocean#446]
### Terraform Version
Terraform v0.12.25

### Affected Resource(s)
Please list the resources as a list, for example:
- VPC

### Terraform Configuration Files
same as [issue 445](https://github.com/terraform-providers/terraform-provider-digitalocean/issues/445)

### Debug Output
```
digitalocean_kubernetes_cluster.flexvoucher: Destroying... [id=018f6159-3618-46c8-8dac-5f6e6ad13270]
digitalocean_database_user.flexvoucher: Destruction complete after 4s
digitalocean_database_cluster.flexvoucher: Destroying... [id=ee01c967-4ae8-4d6c-9d96-20f73b06a3ff]
digitalocean_kubernetes_cluster.flexvoucher: Destruction complete after 1s
digitalocean_database_cluster.flexvoucher: Destruction complete after 1s
digitalocean_volume_attachment.mongodata: Still destroying... [id=194391368-9bb586e8-a3d5-11ea-aed1-0a58ac14d008-20200601070128695300000001, 10s elapsed]
digitalocean_droplet.elasticsearch: Still destroying... [id=194391366, 10s elapsed]
digitalocean_droplet.bastion: Still destroying... [id=194391367, 10s elapsed]
digitalocean_volume_attachment.mongodata: Destruction complete after 12s
digitalocean_volume.mongodata: Destroying... [id=9bb586e8-a3d5-11ea-aed1-0a58ac14d008]
digitalocean_droplet.mongo: Destroying... [id=194391368]
digitalocean_volume.mongodata: Destruction complete after 1s
digitalocean_droplet.elasticsearch: Still destroying... [id=194391366, 20s elapsed]
digitalocean_droplet.bastion: Still destroying... [id=194391367, 20s elapsed]
digitalocean_droplet.mongo: Still destroying... [id=194391368, 10s elapsed]
digitalocean_droplet.elasticsearch: Destruction complete after 22s
digitalocean_droplet.bastion: Destruction complete after 21s
digitalocean_droplet.mongo: Still destroying... [id=194391368, 20s elapsed]
digitalocean_droplet.mongo: Destruction complete after 23s
digitalocean_vpc.flexvoucher: Destroying... [id=77c8159d-a141-4837-b358-145953f64fb0]
digitalocean_vpc.flexvoucher: Still destroying... [id=77c8159d-a141-4837-b358-145953f64fb0, 10s elapsed]
digitalocean_vpc.flexvoucher: Still destroying... [id=77c8159d-a141-4837-b358-145953f64fb0, 20s elapsed]
digitalocean_vpc.flexvoucher: Still destroying... [id=77c8159d-a141-4837-b358-145953f64fb0, 30s elapsed]
digitalocean_vpc.flexvoucher: Still destroying... [id=77c8159d-a141-4837-b358-145953f64fb0, 40s elapsed]
digitalocean_vpc.flexvoucher: Still destroying... [id=77c8159d-a141-4837-b358-145953f64fb0, 50s elapsed]

Error: DELETE https://api.digitalocean.com/v2/vpcs/77c8159d-a141-4837-b358-145953f64fb0: 403 (request "7ae089e4-65cb-410b-9cf2-3cc9abdfb8cc") Can not delete VPC with members
```

### Expected Behavior
VPC should be deleted.

### Actual Behavior
VPC is not deleted. In DO web GUI - kubernetes cluster, although deleted, stays for a couple of minutes after deletion as a resource of VPC. So, if the cluster is deleted by the same `terraform destroy` call - digitalocean_vpc hits probably a timeout.

This behaviour can be also reproduced on DO web GUI. Create VPC, k8s cluster, assign cluster to VPS, delete cluster and immediately delete VPC - error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. `terraform destroy`

**Comment by halkyon** [comment]
Ran into the same problem, I initially thought it should wait for the API to return a 404, but the resources are still there. If the API was to return a 200 "Deleting" state then Terraform could wait until it's finished deleting before moving onto deleting the VPC. Maybe this was a deliberate design decision, I'm not sure.

**Comment by andrewsomething** [comment]
@halkyon I'd accept a pull request with changes along those lines. Though I suspect that this specific issue is more general. There seems to be a bit of a lag between when a resource is deleted and when it is de-registered from the VPC service. We do have a retry in place in the case of a 403 response, but we might want to increase the timeout on it.

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_vpc.go#L151-L161

**Comment by sanflores** [comment]
Hi @andrewsomething, thanks for the change increasing the timeout to 2 minutes, but how can I change that default time as I'm still getting that error while deleting a VPC right after deleting a k8s cluster. Thank you!

**Comment by andrewsomething** [comment]
Hi @sanflores,

You can configure a custom timeout for deletion using something like:

```hcl
resource "digitalocean_vpc" "example" {
  name     = "example-project-network"
  region   = "nyc3"

  timeouts {
    delete = "30m"
  }
}
```

https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts

**Comment by dev-ago** [comment]
Hello,

I had the same problem and I managed to solve it with the Terraform time_sleep module at the time of Destroy.

This gives time to the digital ocean API to finish all the resources that are members of the VPC.

Here is the code I use in my Pipeline:


```
# vpc.tf
resource "digitalocean_vpc" "sandbox" {
  name = "sandbox"
  region = var.region
  ip_range = var.ip_range
}
resource "time_sleep" "wait_300_seconds_to_destroy" {
  depends_on = [digitalocean_vpc.sandbox]
  destroy_duration = "300s"
}
resource "null_resource" "placeholdet" {
  depends_on = [time_sleep.wait_300_seconds_to_destroy]
}

```

https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep
