### ISSUE TITLE
remote-exec is not working 

### ISSUE THREAD

**Issue by dgonti0507** [terraform-providers/terraform-provider-digitalocean#452]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
2020/06/14 06:15:06 [TRACE] EvalWriteState: writing current state object for aws_volume_attachment.install2
2020/06/14 06:15:06 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/06/14 06:15:06 [TRACE] EvalApplyProvisioners: provisioning aws_volume_attachment.install2 with "remote-exec"
remote-exec-provisioner (internal) 2020/06/14 06:15:06 [DEBUG] connecting to remote shell using WinRM
remote-exec-provisioner (internal) 2020/06/14 06:15:06 [DEBUG] Uploading file to 'C:/Temp/terraform_1928644706.cmd'
2020/06/14 06:15:09 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "aws_ami_from_instance.SQLAMI"
2020/06/14 06:15:09 [TRACE] dag/walk: vertex "provider.aws (close)" is waiting for "aws_ami_from_instance.SQLAMI"
2020/06/14 06:15:09 [TRACE] dag/walk: vertex "root" is waiting for "provisioner.remote-exec (close)"

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
on remote- exec , it is uploading bat file on to c:\temp folder but executing on second run.

on first run, remote-exec is working as expected like uplaoding file , and excuting it.

### Actual Behavior
What actually happened?

not running remote exec commands. 

But if stop the process and running just that remote exec commands working with out any issue.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by dgonti0507** [comment]
debug lines  where the issue is 
**2020/06/14 06:15:06 [TRACE] EvalWriteState: writing current state object for aws_volume_attachment.install2
2020/06/14 06:15:06 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/06/14 06:15:06 [TRACE] EvalApplyProvisioners: provisioning aws_volume_attachment.install2 with "remote-exec"
remote-exec-provisioner (internal) 2020/06/14 06:15:06 [DEBUG] connecting to remote shell using WinRM
remote-exec-provisioner (internal) 2020/06/14 _06:15:06_ [DEBUG] Uploading file to 'C:/Temp/terraform_1928644706.cmd'
2020/06/14 06:15:09 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "aws_ami_from_instance.SQLAMI"
2020/06/14 06:15:09 [TRACE] dag/walk: vertex "provider.aws (close)" is waiting for "aws_ami_from_instance.SQLAMI"
2020/06/14 06:15:09 [TRACE] dag/walk: vertex "root" is waiting for "provisioner.remote-exec (close)"**


First remote_exec 
2020/06/14 06:13:17 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/06/14 06:13:17 [TRACE] EvalApplyProvisioners: provisioning null_resource.reboot_instance with "remote-exec"
remote-exec-provisioner (internal) 2020/06/14 06:13:17 [DEBUG] connecting to remote shell using WinRM
remote-exec-provisioner (internal) 2020/06/14 06:13:17 [DEBUG] Uploading file to 'C:/Temp/terraform_991839999.cmd'
remote-exec-provisioner (internal) 2020/06/14 06:13:18 [DEBUG] starting remote command: C:/Temp/terraform_991839999.cmd
remote-exec-provisioner (internal) 2020/06/14 06:13:18 [DEBUG] Uploading file to 'C:/Temp/terraform_991839999.cmd'
2020/06/14 06:13:19 [TRACE] dag/walk: vertex "provisioner.local-exec (close)" is waiting for "null_resource.reboot_instance"
2020/06/14 06:13:19 [TRACE] dag/walk: vertex "provider.aws (close)" is waiting for "aws_ami_from_instance.SQLAMI"

**Comment by andrewsomething** [comment]
Hi @dgonti0507,

You debug output implies that you are using the AWS provider, not DigitalOcean. If that's the case please report the issue at: 

https://github.com/terraform-providers/terraform-provider-aws

If I've misunderstood your issue and it is indeed about the DigitalOcean Terraform provider, please feel free to reopen this with additional information about the problem.
