### ISSUE TITLE
Spaces resource created by container registry urn

### ISSUE THREAD

**Issue by survivorbat** [terraform-providers/terraform-provider-digitalocean#454]
### Terraform Version
0.12.26

### Affected Resource(s):
- digitalocean_container_registry

### Terraform Configuration Files
```hcl
resource "digitalocean_project" "project" {
  name        = "OLC"
  resources = [...]
}

resource "digitalocean_container_registry" "container_registry" {
  name = "myregistry"
}
```

### Feature

When you create a container registry, another Spaces resource is created that is used to house your files. This Spaces object appears in your default project and as far as I can tell, there is no way to get the **urn** of the registry's associated Spaces object, meaning that I can't use Terraform to put this Spaces object in a different project. There are also no tags on the spaces object and the name is randomly generated, so I can't do any kind of lookup.

I'd love to have something like:
```hcl
resource "digitalocean_project" "project" {
  name        = "OLC"
  resources = [
    digitalocean_container_registry.container_registry.space.urn
  ]
}

resource "digitalocean_container_registry" "container_registry" {
  name = "myregistry"
}
```

I might just be missing something in the documentation, I'd love to hear whether there's already a way to accomplish this.

Your sincerely, survivorbat

**Comment by andrewsomething** [comment]
Thanks for raising this issue. The DigitalOcean container registry is still in early availability. I've confirmed with the DO registry team that the plan is for the Spaces resource that is created when you create a registry to be hidden before it enters general availability. While you can move the Space to a different project, it is not intended to be managed directly by a user. At GA, the fact that Spaces is used for storage just be a technical detail that is not visible.

**Comment by survivorbat** [comment]
> Thanks for raising this issue. The DigitalOcean container registry is still in early availability. I've confirmed with the DO registry team that the plan is for the Spaces resource that is created when you create a registry to be hidden before it enters general availability. While you can move the Space to a different project, it is not intended to be managed directly by a user. At GA, the fact that Spaces is used for storage just be a technical detail that is not visible.

I see! Thanks for the info, I had a feeling that it'd be hidden eventually since deleting it breaks the registry entirely. I'll wait patiently for it to be hidden :)
