### ISSUE TITLE
it's possible use without terraform app?

### ISSUE THREAD

**Issue by sebastianwebber** [terraform-providers/terraform-provider-digitalocean#46]
Hi there,

sorry for asking here, and please, let me know if there is a better place to ask.

It's possible to call this plugin without the `terraform` cli?

I'm trying to use this plugin in a custom app in golang that launches some machines on Digital Ocean. It's possible to use it without the terraform?

Any advise here?

thanks

**Comment by danrabinowitz** [comment]
Sounds like you might want this instead: https://github.com/digitalocean/godo

**Comment by andrewsomething** [comment]
Like Dan suggested, using godo directly is your best bet for creating DO resources with Go. Please feel free to open a new issue if you have additional questions about the DigitalOcean Terraform provider.
