### ISSUE TITLE
Digital Ocean Provider Seems to Choke on Captcha 

### ISSUE THREAD

**Issue by rtizzy** [terraform-providers/terraform-provider-digitalocean#54]
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
Digital Ocean

### Terraform Configuration Files
N/A
### Debug Output
https://gist.github.com/elricsfate/20e0f30aa2bf4acc0ac12de044554499

### Expected Behavior
After a successful plan, an apply should apply the requested changes

### Actual Behavior
An error occurs as seen in the gist. 

This seems to occur due to a captcha request. 

### Steps to Reproduce
Initiate a plan. 
Plan succeeds. 
Apply the plan. 
Failture. 

### References
This may be somehow related to 

https://github.com/digitalocean/godo/issues/142

**Comment by elricsfate** [comment]
This appears to be an upstream issue with Digital Ocean itself. 

I've attempted to use doctl and run into the same issue. 

I've opened a ticket with DO regarding this issue but if anyone else happens to work there or knows someone that does, that probably doesn't hurt :P

**Comment by danrabinowitz** [comment]
I can take a look. Where's the ticket you opened with DO?

**Comment by elricsfate** [comment]
@danrabinowitz 

Apologies, I never saw this message. The ticket has already been closed. If you'd like I can dig up the ticket number. 

Not sure if this is something that should be fixed in the provider or if DO should possibly ignore captcha requirements for API requests.

**Comment by andrewsomething** [comment]
On the DigitalOcean end, we should never be displaying a captcha on the API. On the Terraform side, we just pulled in the latest version of godo. It now handles the edge case where the API returns a non-JSON response better. See: https://github.com/digitalocean/godo/pull/156

If you or anyone else sees similar behavior in the future, please open a ticket with DigitalOcean support as it is certainly not intended! :smile: 

Thanks for baring with us!
