### ISSUE TITLE
Updating existing DNS record names fails with error about data field needing to end with a .

### ISSUE THREAD

**Issue by chrisbalmer** [terraform-providers/terraform-provider-digitalocean#58]
When updating existing DNS records on DigitalOcean, changing the name of the record results in this error:

```
Error: Error applying plan:

1 error(s) occurred:

* module.digitalocean_records_<domain>.digitalocean_record.msoid: 1 error(s) occurred:

* digitalocean_record.msoid: Failed to update record: PUT https://api.digitalocean.com/v2/domains/<domain>/records/<record_id>: 422 Data needs to end with a dot (.)
```

In looking over the API reference, it appears the `data` field needs to be populated. This is the `value` field in the resource. Even though `value` hasn't changed, it needs to be supplied to the API as `data`. Since no `data` field is supplied, there is no `.` at the end of it. I tested this with curl to verify that not supplying it caused the same error and just adding that one extra field with the existing value fixed it.

[API reference](https://developers.digitalocean.com/documentation/v2/#update-a-domain-record)

`data` is a required field for updating these records:

A, AAAA, CAA, CNAME, MX, TXT, SRV, NS

### Terraform Version
Terraform v0.11.0
+ provider.digitalocean v0.1.2

### Affected Resource(s)

- digitalocean_record

### Terraform Configuration Files

Starting resource:

```hcl
resource "digitalocean_record" "msoid" {
  domain  = "${var.domain_name}"
  name    = "msoid"
  type    = "CNAME"
  ttl     = "300"
  value   = "clientconfig.microsoftonline-p.net."
}
```

Example change to cause error:

```hcl
resource "digitalocean_record" "msoid" {
  domain  = "${var.domain_name}"
  name    = "msoid.test"
  type    = "CNAME"
  ttl     = "300"
  value   = "clientconfig.microsoftonline-p.net."
}
```

### Expected Behavior

The record name should have been changed to `msoid.test`.

### Actual Behavior

```
* digitalocean_record.msoid: Failed to update record: PUT https://api.digitalocean.com/v2/domains/<domain>/records/<record_id>: 422 Data needs to end with a dot (.)
```

### Steps to Reproduce

1. `terraform apply`
2. Change record name
3. `terraform apply`

**Comment by llaski** [comment]
I'm experiencing the same error for MX records.

**Comment by joelchrist** [comment]
Experiencing the same error, any update on this?

**Comment by RuslanZavacky** [comment]
Same problem here. No merges since 8 of Jan... I wonder @tombuildsstuff are you still maintaining it? There are so many great PRs awaiting merge :)

**Comment by tritao** [comment]
Same here.

**Comment by berisberis** [comment]
Same here.

**Comment by andrew-waters** [comment]
Same issue here

**Comment by andrew-waters** [comment]
I've had a look around and I think that the error is caused by the `data` field not being set in https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_record.go#L230-L241

The repo has validation for this on create (https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_record.go#L173-L178) and according to the API docs the data field is required on a `PUT`.
