### ISSUE TITLE
Terraform detects change between record and local state file

### ISSUE THREAD

**Issue by TheYorkshireDev** [terraform-providers/terraform-provider-digitalocean#62]
### Terraform Version
**Versions:**
Terraform: v0.11.1
Digitalocean provider: v0.1.3

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_record

### Terraform Configuration Files
Two small files to reproduce:

_main.tf_ 
```hcl
provider "digitalocean" {
  token = "${var.digitalocean_token}"
}

resource "digitalocean_domain" "domain" {
  name       = "${var.domain}"
  ip_address = "${var.ip_address}"
}

resource "digitalocean_record" "www" {
  domain = "${digitalocean_domain.domain.name}"
  type   = "CNAME"
  name   = "www"
  value  = "@"
  ttl    = "43200"
}
```

_vars.tf_
```hcl
variable "digitalocean_token" {
  description = "The token used to authenticate against the Digital Ocean environment"
  default = "COPYPASTE"
}

variable "domain" {
  description = "The domain to add to digital ocean"
  default = "COPYPASTE"
}

variable "ip_address" {
  description = "The ip address to direct traffic too"
  default = "COPYPASTE"
}
```

### Expected Behavior
After the initial creation of the resource with `terraform apply`, any subsequent `terraform apply` or `terraform plan` should show up with no changes required.

### Actual Behavior
After the initial creation whenever I do `terraform plan` or `terraform apply` changes are found which cause the resource to be destroyed and recreated. This should not be the case. Ignoring the fact the resource is destroyed and recreated, terraform should not detect any changes between `terraform.tfstate` & Digital Ocean.

The output from the simple files above is:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

digitalocean_domain.domain: Refreshing state... (ID: example.domain)
digitalocean_record.www: Refreshing state... (ID: ######)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ digitalocean_record.www (new resource required)
      id:       "######" => <computed> (forces new resource)
      domain:   "example.domain" => "example.domain"
      fqdn:     "www.example.domain" => <computed>
      name:     "www" => "www"
      port:     "0" => <computed>
      priority: "0" => <computed>
      ttl:      "43200" => "43200"
      type:     "CNAME" => "CNAME"
      value:    "example.domain." => "@" (forces new resource)
      weight:   "0" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Steps to Reproduce
Using `main.tf` & `vars.tf` above
1. `terraform apply` (Initial Create)
1. `terraform plan`

**Comment by txomon** [comment]
The problem here is that `value:    "example.domain." => "@" (forces new resource)` forces a new resource. I found that by specifying `name = "@"` attribute I was able to solve it... although I agree makes no sense, maybe you are interested in a workaround.

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
