### ISSUE TITLE
TERRAFORM CRASH when `private_networking = true` after initial droplet creation

### ISSUE THREAD

**Issue by petervandenabeele** [terraform-providers/terraform-provider-digitalocean#67]
Detailed stderr log at https://gist.github.com/petervandenabeele/c9949fa4590086b998683b1184095755
Detailed crash log at
https://gist.github.com/petervandenabeele/0e788d498c5170a3281b208ede11fdff

Version:
```
Terraform v0.11.3
+ provider.digitalocean v0.1.3
```
1. plan + apply of a Droplet without private_networking: OK

2. Added `private_networking = true`

3. plan => correct (?)
```
 ~ digitalocean_droplet.test
      private_networking: "" => "true"
```
4. apply => CRASH "panic: interface conversion: interface {} is bool, not string"

See log gist for detailed crash log

5. On a more general note, can a DigitalOcean Droplet even be converted to private networking after it is created ?

**Comment by andrewsomething** [comment]
I am able to reproduce this.

> On a more general note, can a DigitalOcean Droplet even be converted to private networking after it is created ?

Yes, private networking can be enabled on an existing Droplet. It requires a call to `/v2/droplets/$DROPLET_ID/actions` Though there are a some important things to note:

* Currently no support to _disable_ private networking.
* Enabling private networking on an existing Droplet requires shutting it down.
* It also requires additional configuration on the Droplet. See: https://www.digitalocean.com/community/tutorials/how-to-enable-digitalocean-private-networking-on-existing-droplets

**Comment by sosedoff** [comment]
Im having the same issue, where `terraform apply` will crash if i set the `private_networking = true`. I was able to reproduce the crash multiple times. 

```
Terraform v0.11.7
+ provider.digitalocean v0.1.3
```

However, after the crash terraform no longer has the droplet resources in its state. So running `terraform apply` again will actually create a new set of droplets. Here's my example snippet:

```
provider "digitalocean" {
  token = "${var.token}"
}

resource "digitalocean_ssh_key" "default" {
  name       = "tf_key"
  public_key = "${file("./key.pub")}"
}

resource "digitalocean_droplet" "web" {
  count              = 3
  name               = "web-${count.index}"
  image              = "ubuntu-16-04-x64"
  region             = "nyc3"
  size               = "1gb"
  private_networking = true
}
```

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
