### ISSUE TITLE
remote-exec is not working as expected

### ISSUE THREAD

**Issue by atif089** [terraform-providers/terraform-provider-digitalocean#91]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
```hcl

provider "digitalocean" {
  token = "..."
}

# Upload a SSH Key
resource "digitalocean_ssh_key" "default" {
  name       = "Terra SSH Key"
  public_key = "${file("${path.root}/../../ssh/id_rsa.pub")}"
}

# Create a web server
resource "digitalocean_droplet" "main-instance" {
  image              = "wordpress-16-04"
  name               = "web-1"
  region             = "ams3"
  size               = "s-1vcpu-1gb"
  backups            = false
  private_networking = true
  backups            = false
  ipv6               = false
  ssh_keys           = ["${digitalocean_ssh_key.default.fingerprint}"]

  connection {
    user        = "root"
    type        = "ssh"
    private_key = "${file("${path.root}/../../ssh/id_rsa")}"
  }

  provisioner "remote-exec" {
    inline = [ "sleep 30" ]
  }

  provisioner "remote-exec" {
    script = "${path.root}/init-scripts.sh"
  }
```

### Debug Output
https://gist.github.com/atif089/7b0f0217a87cb07f1b409a0a4849d17f#file-tf-log

### Expected Behavior
Remote-Exec script should have uploaded and executed

### Actual Behavior
Remote-Exec script was not uploaded and the following error was reported

`digitalocean_droplet.main-instance: Failed to upload script: lease wait while we get your droplet ready...`

### Steps to Reproduce
1. `terraform apply`

**Comment by atif089** [comment]
Update.

I think the reason for this nor working is that remote-exec is trying execution a bit too early. I fixed this by adding a workaround local-exec provisioner to wait for a few more seconds.

  provisioner "local-exec" {
    command = "ping 127.0.0.1 -n 30 > nul"
    on_failure = "continue"
  }

**Comment by danreeves** [comment]
I'm getting this issue and the suggested workaround doesn't help

**Comment by atif089** [comment]
@danreeves are you on Linux. In that case, you would need

```
provisioner "local-exec" {
  command = "sleep 30"
  on_failure = "continue"
}
```

@andrewsomething Do you think this should be closed before fixing? The workaround works but I think it needs to be fixed so that we don't have to add this.

**Comment by atif089** [comment]
@danreeves Looks good to me. You can try removing the `on_failure` line. If there is any problem with the sleep command it should break before the `remote-exec`

**Comment by danreeves** [comment]
No difference. Here's what the output looks like for that part, as you can see `sleep 30` doesn't block.

```
digitalocean_droplet.www-1: Still creating... (1m0s elapsed)
digitalocean_droplet.www-1: Provisioning with 'local-exec'...
digitalocean_droplet.www-1 (local-exec): Executing: ["/bin/sh" "-c" "sleep 30"]
digitalocean_droplet.www-1: Still creating... (1m10s elapsed)
digitalocean_droplet.www-1: Still creating... (1m20s elapsed)
digitalocean_droplet.www-1: Still creating... (1m30s elapsed)
digitalocean_droplet.www-1: Provisioning with 'remote-exec'...
```

**Comment by atif089** [comment]
Try increasing the timeout. I'm assuming DO is taking more than 30 seconds to create the droplet. I can see `sleep 30` executing fine

**Comment by danreeves** [comment]
Ah, you're totally right, I didn't understand the output. Upped the timeout and it worked. This really shouldn't be necessary though so I'd vote for re-opening the ticket.

Thanks for the help!

**Comment by andrewsomething** [comment]
Unfortunately, I don't think there is much we can do here from the provider side. All we do in the provider is set the IP address for use in the connection once the API reports the Droplet is ready:

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/5f345954158b2bf86fae5369b1a75d5d1e30bba3/digitalocean/resource_digitalocean_droplet.go#L345

The connection and provisioner are part of upstream Terraform core.

I think `Still creating...` here is a bit misleading, as the resource is not considered "created" until the provisioner completes. So by the time you see `Provisioning with 'remote-exec'...` in the output, the Droplet has been created on the DigitalOcean side. So the root issue is something with the SSH connection to the Droplet.

@danreeves Are you also trying to use this with a One-Click app like @atif089's example? If so, can you reproduce with a standard Ubuntu image? `Please wait while we get your droplet ready...` leads me to believe that the One-Click is blocking SSH connections until it has completed its own internal provisioning scripts (e.g configuring Wordpress).

Another potential workaround for this that might be a bit more elegant is to provide the script you want to run in the Droplet's `user_data` attribute. That way, an SSH connection is not needed. See: https://www.digitalocean.com/docs/droplets/resources/metadata/

There is probably also a feature request to Terraform itself to allow setting a number of retries on thee remote-exec provisioner.

**Comment by danreeves** [comment]
Yeah I was using a One-click App image. It works perfectly with the plain `debian-9-x64` image. I guess I'll do the installs and setup I need myself which is a shame but not a big deal. Thanks again!
