### ISSUE TITLE
Resource 'digitalocean_droplet.droplet' does not have attribute 'ipv4_address_private'

### ISSUE THREAD

**Issue by mr-yaky** [terraform-providers/terraform-provider-digitalocean#92]
Hi,

I try use droplet module from github:
https://github.com/antarctica/terraform-module-digital-ocean-droplet

And always get an error about unset attribute.
I know that I can use my own custom module and just comment/remove following lines:
```
output "ip_v4_address_private" {
    value = "${digitalocean_droplet.droplet.ipv4_address_private}"
}
```
But I think it will be great to fix it on provider level because it will be useful for dynamic resource's configurations for using with modules even if `private_networking` is `false`.
Also may be you know some other nice workaround to solve this problem while this will be fixed on provider level ? 

### Terraform Version
Terraform v0.11.7
+ provider.digitalocean v0.1.3

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.11.7"
}

provider "digitalocean" {
    version = "~> 0.1.3"
    token   = "${var.digitalocean_token}"
}

variable "digitalocean_token" {
  type = "string"
  default = ""
  description = "DigitalOcean API Token"
}

variable "ssh_fingerprints" {
    default = [
        "blah"
    ]
}

module "vm01" {
    source = "github.com/antarctica/terraform-module-digital-ocean-droplet?ref=v1.2.0"
#    source = "./droplet"
    hostname = "vm01"
    image = "centos-7-x64"
    region = "lon1"
    size = "1gb"
    private_networking = "false"
    ssh_fingerprints = "${var.ssh_fingerprints}"
}

```

### Error Output
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

digitalocean_droplet.droplet: Refreshing state... (ID: 12345678)

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.pgsql01.output.ip_v4_address_private: Resource 'digitalocean_droplet.droplet' does not have attribute 'ipv4_address_private' for variable 'digitalocean_droplet.droplet.ipv4_address_private'
```

### Expected Behavior
ipv4_address_private should be set and should be a null even if `private_networking` is `false`.

### Actual Behavior
always get an error: 
```
does not have attribute 'ipv4_address_private' for variable 'digitalocean_droplet.droplet.ipv4_address_private'
```
### Steps to Reproduce
`terraform plan`
`terraform apply`

and then again run:
`terraform plan`

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
