### ISSUE TITLE
Firewall Droplet IDs » Support for Dynamic Data via Data Sources

### ISSUE THREAD

**Issue by rahiparikh** [terraform-providers/terraform-provider-digitalocean#96]
Hi there,

Terraform DigitalOcean provider does not support dynamic data via data source for firewall module.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_firewall

### Terraform Configuration Files
_globals/data.tf_
```
data "digitalocean_droplet" "all_nix" {
  filter {
    name   = "tag:osFlavor_nix"
    values = ["osFlavor_nix"]
  }

  filter {
    name        = "tag:terraform_yes"
    values      = ["terraform_yes"]
  }
}
```

_globals/firewall.tf_
```
resource "digitalocean_firewall" "22.tcp.ssh" {
  name        = "security-group_all_all_all"
  droplet_ids = "${data.digitalocean_droplet.all_nix.*.id}"

  inbound_rule = [
    {
      protocol    = "tcp"
      port_range  = "22"
      source_tags = ["${var.vpn_concentrator}"]
    },
  ]
}
```

_services/BLAH.tf_
```
resource "digitalocean_droplet" "BLAH" {
  count              = "2"
  ssh_keys           = ["<VAL>"]
  image              = "ubuntu184"
  size               = "c-2"
  region             = "nyc1"
  private_networking = true
  backups            = false
  ipv6               = false
  name               = "BLAH${count.index}"
  tags               = ["${var.osFlavor_nix}", "${var.terraform_yes}"]
}
```

_A few other files have been omitted for simplicity._

### Debug Output
```
terraform plan
Error: module.globals.data.digitalocean_droplet.all_nix: Provider doesn't support data source: digitalocean_droplet
Error: module.globals.digitalocean_firewall.security-group_all_all_all_22_tcp_ssh: droplet_ids: should be a list
```

### Expected Behavior
The provider should statically and dynamically be able to identify and assign the ids to firewall as certain FW rules are of global nature and would require one to apply to large number of droplets based on their tags/dc location etc.

**Comment by andrewsomething** [comment]
Hi @rahiparikh, thanks for the report. Just to be clear, is the `digitalocean_droplet` datasource in your example something implemented by a third-party module or is this a request to implement a `digitalocean_droplet` datasource?

Currently, the supported way to dynamically add or remove a firewall from a Droplet is via tags. For example:

```
resource "digitalocean_tag" "web-frontend" {
    name = "web-frontend"
}

resource "digitalocean_firewall" "web-mgmt-firewall" {
    name = "web-mgmt-firewall"
    tags = [ "web-frontend" ]

    inbound_rule = [
        {
            protocol         = "tcp",
            port_range       = "22",
            source_addresses = [ "0.0.0.0/0", "::/0" ]
        },
    ]
}

resource "digitalocean_droplet" "web-frontend" {
    count              = 3
    image              = "ubuntu-17-10-x64"
    name               = "web-${count.index + 1}"
    region             = "nyc3"
    size               = "1gb"
    tags               = ["${digitalocean_tag.web-frontend.id}"]
    private_networking = true
    monitoring         = true
}
```

**Comment by rahiparikh** [comment]
@andrewsomething Thanks for quick reply. `digitalocean_droplet` datasource is something that I created and imported as a module. However, `digitalocean_droplet` datasource and it support for  various parameters is what I am requesting. 

The current example that you provided works great but I am not sure if it results will be union or intersection of droplets that are identified by more than one tags. Also, I couldn't infer that from https://www.terraform.io/docs/providers/do/r/firewall.html#tags as well.

**Comment by andrewsomething** [comment]
> I am not sure if it results will be union or intersection of droplets that are identified by more than one tags. Also, I couldn't infer that from https://www.terraform.io/docs/providers/do/r/firewall.html#tags as well.

Those docs could definitely be improved. It's a union. I'm guessing you're looking for an intersection?

What does the output of `digitalocean_droplet` look like? Have you tried:

```
droplet_ids = ["${data.digitalocean_droplet.all_nix.*.id}"]
```

**Comment by rahiparikh** [comment]
I guess, filtering depends on the situation - sometimes you need union and other times you need intersection; in this case, I was looking for intersection.

The output after change gives an error "Error: module.globals.data.digitalocean_droplet.all_nix: Provider doesn't support data source: digitalocean_droplet".

**Comment by andrewsomething** [comment]
We now have a `digitalocean_droplets` data source that returns a filterable list. The most recent release contains a bug fix for it that now allows it to fill the use case. For example:

```
data "digitalocean_droplets" "list" {
  filter {
    key    = "tags"
    values = ["web"]
  }
}

resource "digitalocean_firewall" "web-80-all" {
  name        = "web-80-all"
  droplet_ids = data.digitalocean_droplets.list.droplets.*.id

  inbound_rule {
    protocol         = "tcp"
    port_range       = "80"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }
}
```

https://www.terraform.io/docs/providers/do/d/droplets.html
